import { deployScript } from "../rocketh/deploy.js";
import { project } from "../.ethoko-typings/index.js";
import * as RockethTypes from "rocketh/types";

/**
 * This deployment script deploys the Counter contract targeting a specific release.
 *
 * The compilation artifacts are retrieved from the Ethoko project registry for the specified release.
 * The artifacts are **frozen** at the time of the release, ensuring consistent deployments.
 * Local modifications to the contract source code or any new compilation, releases etc.. will not affect this deployment.
 *
 * The `Counter` contract is deployed first.
 * The deployment is done using `hardhat-deploy@v2`.
 *
 * This script relies on typings generated by Ethoko for the project "forge-counter".
 * It is assumed that the tag `2026-02-04` exists in the Ethoko registry for this project.
 * It could have been created by running:
 * ```
 * npx ethoko push --tag 2026-02-04 --artifact-path ./out
 * ```
 * The assumed commands that have been run prior to this deployment are:
 *  - `npx ethoko pull` to pull the project from the Ethoko registry,
 *  - `npx ethoko typings` to generate the typings for the project.
 */

const TARGET_RELEASE = "2026-02-04";

export default deployScript(
  async ({ deploy, namedAccounts }) => {
    const { deployer } = namedAccounts;

    // Get project utilities for the target release
    const projectUtils = project("forge-counter").tag(TARGET_RELEASE);

    const counterArtifact = await projectUtils.getContractArtifact(
      "src/Counter.sol:Counter",
    );

    await deploy(`Counter@${TARGET_RELEASE}`, {
      account: deployer,
      artifact: {
        abi: scopeAbi(counterArtifact.abi),
        bytecode: counterArtifact.bytecode,
        metadata: counterArtifact.metadata,
        // | | | | | | | | | | | | | |
        // | | | Optional fields | | |
        // v v v                 v v v
        deployedBytecode: counterArtifact.deployedBytecode,
        linkReferences: counterArtifact.linkReferences,
        deployedLinkReferences: counterArtifact.deployedLinkReferences,
        contractName: counterArtifact.contractName,
        sourceName: counterArtifact.sourceName,
        devdoc: counterArtifact.devdoc as RockethTypes.DevDoc | undefined,
        evm: counterArtifact.evm,
        storageLayout: counterArtifact.storageLayout as
          | RockethTypes.StorageLayout
          | undefined,
        userdoc: counterArtifact.userdoc as RockethTypes.UserDoc | undefined,
      },
    });
  },
  { tags: ["Counter", "Counter_deploy", TARGET_RELEASE] },
);

// Scoping method in order to handle the case of empty typings have been generated, e.g. in CI
function scopeAbi<T>(
  abi: T,
): T extends RockethTypes.Abi ? T : RockethTypes.Abi {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return abi as any;
}
