import { createHash } from "node:crypto";

import { createSpinner } from "../cli-ui/utils";
import { LocalStorage } from "../local-storage";
import { toAsyncResult } from "../utils/result";
import { CliError } from "./error";
import { lookForBuildInfoJsonFile } from "./helpers/look-for-build-info-json-file";
import { mapBuildInfoToEthokoArtifact } from "./helpers/map-build-info-to-ethoko-artifact";
import { EthokoOutputArtifact } from "@/utils/ethoko-artifacts-schemas/v0";
import type { BuildInfoPath } from "./helpers/look-for-build-info-json-file";

function buildInfoPathToSuccessText(buildInfoPath: BuildInfoPath): string {
  if (buildInfoPath.format === "hardhat-v3") {
    return `Hardhat v3 compilation artifact found`;
  }
  if (buildInfoPath.format === "hardhat-v2") {
    return `Hardhat v2 compilation artifact input file found at ${buildInfoPath.buildInfoPath}`;
  }
  if (
    buildInfoPath.format === "forge-v1-default" ||
    buildInfoPath.format === "forge-v1-with-build-info-option"
  ) {
    return `Forge compilation artifact found at ${buildInfoPath.buildInfoPath}`;
  }
  throw new Error(
    `Unsupported build info format: ${buildInfoPath.format satisfies never}`,
  );
}
/**
 * This script generates the differences between the artifacts generated by a fresh compilation and the ones of a pulled artifact.
 *
 * The fresh artifacts are represented by the file at `artifacts/build-info/<build info hash>.json`.
 * The `latest` artifacts are represented by the file at `<Ethoko directory>/<release>/build-info.json`.
 *
 * For each build info file, the script will parse the `output.contracts` object.
 * This object contains as keys the path of a contract file and as values the contracts within it, i.e.
 * ```
 * {
 *  "output": {
 *   "contracts": {
 *      "path/to/foo.sol": {
 *         "Foo": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         }
 *      },
 *      "path/to/bar.sol": {
 *         "Bar1": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         },
 *         "Bar2": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         },
 *      },
 *   }
 * }
 * ```
 *
 * For each contract, a hash is computed based on
 * - stringified abi,
 * - bytecode object,
 * - metadata
 * This hash is stored in a map with the `<file path><separator constant><contract name>` as key.
 *
 * Comparing the two maps, the script will output the differences between the two sets of contracts.
 */
export type Difference = {
  path: string;
  name: string;
  status: "added" | "removed" | "changed";
};

/**
 * Generates the differences between the artifacts generated by a fresh compilation and the ones of a pulled artifact.
 * It consists of the following steps:
 * 1. Check if the target artifact exists locally, if not throw an error
 * 2. Read the build info file of the fresh compilation artifact and generate the contract hashes map
 * 3. Read the build info file of the target artifact and generate the contract hashes map
 * 4. Compare the two maps and generate the differences array
 *
 * @throws CliError if there is an error during the execution of the steps, with user-friendly messages that can be directly shown to the user
 * @param artifactPath The path to the artifact to compare with,
 * @param artifact The artifact to compare with, containing the project and the tag or id of the target artifact
 * @param localStorage The local storage used to persist pulled artifacts
 * @param opts Options for the diff command
 * @param opts.debug Enable debug mode for more verbose logging
 * @param opts.silent Suppress CLI output (errors and warnings still shown)
 * @param opts.isCI Whether running in CI environment (disables interactive prompts)
 * @returns The array of differences between the fresh compilation artifact and the target artifact
 */
export async function generateDiffWithTargetRelease(
  artifactPath: string,
  artifact: {
    project: string;
    search: { type: "tag"; tag: string } | { type: "id"; id: string };
  },
  localStorage: LocalStorage,
  opts: { debug: boolean; silent?: boolean; isCI?: boolean },
): Promise<Difference[]> {
  // Step 1: Check if target artifact exists locally

  const spinner1 = createSpinner(
    "Checking local artifact existence...",
    opts.silent,
  );
  const ensureResult = await toAsyncResult(
    localStorage.ensureProjectSetup(artifact.project),
    { debug: opts.debug },
  );
  if (!ensureResult.success) {
    spinner1.fail("Failed to setup local storage");
    throw new CliError(
      "Error setting up local storage, is the script not allowed to write to the filesystem? Run with debug mode for more info",
    );
  }

  if (artifact.search.type === "tag") {
    const hasTagResult = await toAsyncResult(
      localStorage.hasTag(artifact.project, artifact.search.tag),
      { debug: opts.debug },
    );
    if (!hasTagResult.success) {
      spinner1.fail("Failed to check local artifacts");
      throw new CliError(
        "Error checking local storage, is the script not allowed to read from the filesystem? Run with debug mode for more info",
      );
    }
    if (!hasTagResult.value) {
      spinner1.fail("Local artifact not found");
      throw new CliError(
        `The artifact "${artifact.project}:${artifact.search.tag}" has not been found locally. Please, make sure to have the artifact locally before running the diff command. Run with debug mode for more info`,
      );
    }
  } else {
    const hasIdResult = await toAsyncResult(
      localStorage.hasId(artifact.project, artifact.search.id),
      { debug: opts.debug },
    );
    if (!hasIdResult.success) {
      spinner1.fail("Failed to check local artifacts");
      throw new CliError(
        "Error checking local storage, is the script not allowed to read from the filesystem? Run with debug mode for more info",
      );
    }
    if (!hasIdResult.value) {
      spinner1.fail("Local artifact not found");
      throw new CliError(
        `The artifact "${artifact.project}:${artifact.search.id}" has not been found locally. Please, make sure to have the artifact locally before running the diff command. Run with debug mode for more info`,
      );
    }
  }
  spinner1.succeed("Local artifact found");

  // Step 2: Look for compilation artifact
  const spinner2 = createSpinner(
    "Looking for compilation artifact...",
    opts.silent,
  );
  const buildInfoPathResult = await toAsyncResult(
    lookForBuildInfoJsonFile(artifactPath, spinner2, {
      debug: opts.debug,
      silent: opts.silent,
      isCI: opts.isCI,
    }),
  );
  if (!buildInfoPathResult.success) {
    spinner2.fail("Failed to find compilation artifact");
    // @dev the lookForBuildInfoJsonFile function throws a CliError with a user-friendly message, so we can directly re-throw it here without wrapping it in another error or modifying the message
    throw buildInfoPathResult.error;
  }
  spinner2.succeed(buildInfoPathToSuccessText(buildInfoPathResult.value));

  // Step 3: Parse the compilation artifact, mapping it to the Ethoko format
  const spinner3 = createSpinner(
    "Analyzing compilation artifact...",
    opts.silent,
  );
  const ethokoArtifactParsingResult = await toAsyncResult(
    mapBuildInfoToEthokoArtifact(buildInfoPathResult.value, opts.debug),
  );
  if (!ethokoArtifactParsingResult.success) {
    spinner3.fail("Unable to handle the provided compilation artifact");
    // @dev the mapBuildInfoToEthokoArtifact function throws an Error with a user-friendly message, so we can directly re-throw it here without wrapping it in another error or modifying the message
    throw ethokoArtifactParsingResult.error;
  }
  const { outputArtifact } = ethokoArtifactParsingResult.value;
  spinner3.succeed("Compilation artifact is valid");

  const virtualReleaseContractHashesResult = await toAsyncResult(
    generateContractHashes(outputArtifact),
    { debug: opts.debug },
  );
  if (!virtualReleaseContractHashesResult.success) {
    spinner3.fail("Failed to analyze compilation artifact");
    throw new CliError(
      "Error generating contract hashes from the fresh compilation artifact. Run with debug mode for more info",
    );
  }
  spinner3.succeed("Fresh artifact loaded");

  const spinner4 = createSpinner("Reading target artifact...", opts.silent);
  const artifactContentResult = await toAsyncResult(
    artifact.search.type === "tag"
      ? localStorage.retrieveOutputArtifactByTag(
          artifact.project,
          artifact.search.tag,
        )
      : localStorage.retrieveOutputArtifactById(
          artifact.project,
          artifact.search.id,
        ),
    { debug: opts.debug },
  );
  if (!artifactContentResult.success) {
    spinner4.fail("Failed to read target artifact");
    throw new CliError(
      "Unable to retrieve the target artifact content, please ensure it exists locally. Run with debug mode for more info",
    );
  }

  const targetReleaseContractHashesResult = await toAsyncResult(
    generateContractHashes(artifactContentResult.value),
    { debug: opts.debug },
  );
  if (!targetReleaseContractHashesResult.success) {
    spinner4.fail("Failed to analyze target artifact");
    throw new CliError(
      "Error generating contract hashes for the target artifact. Run with debug mode for more info",
    );
  }
  spinner4.succeed("Target artifact loaded");

  const spinner5 = createSpinner("Computing differences...", opts.silent);
  const differences: Difference[] = [];
  for (const [
    contractKey,
    contractHash,
  ] of virtualReleaseContractHashesResult.value.entries()) {
    const { contractPath, contractName } = parseKey(contractKey);
    const targetReleaseHash =
      targetReleaseContractHashesResult.value.get(contractKey);
    if (!targetReleaseHash) {
      differences.push({
        path: contractPath,
        name: contractName,
        status: "added",
      });
    } else if (targetReleaseHash !== contractHash) {
      differences.push({
        path: contractPath,
        name: contractName,
        status: "changed",
      });
    }
  }

  for (const contractKey of targetReleaseContractHashesResult.value.keys()) {
    if (!virtualReleaseContractHashesResult.value.has(contractKey)) {
      const { contractPath, contractName } = parseKey(contractKey);
      differences.push({
        path: contractPath,
        name: contractName,
        status: "removed",
      });
    }
  }
  spinner5.succeed("Differences computed");

  return differences;
}

async function generateContractHashes(
  artifact: EthokoOutputArtifact,
): Promise<Map<string, string>> {
  const contractHashes = new Map<string, string>();
  for (const contractPath in artifact.output.contracts) {
    const contracts = artifact.output.contracts[contractPath];
    for (const contractName in contracts) {
      const contract = contracts[contractName];
      if (!contract) {
        throw new Error(
          `Contract ${contractName} in file ${contractPath} is undefined`,
        );
      }
      const hash = hashContract(contract);
      contractHashes.set(formKey(contractPath, contractName), hash);
    }
  }

  return contractHashes;
}

type Contract = EthokoOutputArtifact["output"]["contracts"][string][string];
function hashContract(contract: Contract): string {
  const hash = createHash("sha256");

  contract.abi.sort((a, b) => {
    if (a.type !== b.type) {
      return a.type.localeCompare(b.type);
    }
    if (a.type === "function" && b.type === "function") {
      return a.name.localeCompare(b.name);
    }
    if (a.type === "event" && b.type === "event") {
      return a.name.localeCompare(b.name);
    }
    if (a.type === "error" && b.type === "error") {
      return a.name.localeCompare(b.name);
    }
    if (a.type === "constructor" && b.type === "constructor") {
      return 0;
    }
    if (a.type === "fallback" && b.type === "fallback") {
      return 0;
    }
    if (a.type === "receive" && b.type === "receive") {
      return 0;
    }
    return 0;
  });
  for (const abiItem of contract.abi) {
    hash.update(JSON.stringify(abiItem));
  }

  hash.update(contract.evm.bytecode.object);
  hash.update(contract.metadata);

  return hash.digest("hex");
}

const SEPARATOR = "@@@@";
function formKey(contractPath: string, contractName: string): string {
  return `${contractPath}${SEPARATOR}${contractName}`;
}
function parseKey(key: string): { contractPath: string; contractName: string } {
  const [contractPath, contractName] = key.split(SEPARATOR);
  if (!contractPath || !contractName) {
    throw new Error(`Invalid key: ${key}`);
  }
  return { contractPath, contractName };
}
