// THIS IS AN AUTOGENERATED FILE. EDIT AT YOUR OWN RISKS.
import fs from "node:fs/promises";
import fsSync from "node:fs";
import { PROJECTS, ETHOKO_PATH } from "./summary-exports.js";
import type { ABIs } from "./abis.d.js";

// ######################################################
// ############## PROJECTS RELATED TYPINGS ##############
// ######################################################

type Projects = typeof PROJECTS;
type AccurateProject = keyof Projects;
export type Project = AccurateProject extends never ? string : AccurateProject;

export type Contract<TProject> = TProject extends AccurateProject
  ? keyof Projects[TProject]["contracts"]
  : string;
export type Tag<TProject> = TProject extends AccurateProject
  ? keyof Projects[TProject]["tags"]
  : string;

type AvailableTagForContractAsArray<TProject, TContract> =
  TProject extends AccurateProject
    ? TContract extends Contract<TProject>
      ? Projects[TProject]["contracts"][TContract]
      : string[]
    : string[];

export type AvailableTagForContract<TProject, TContract> =
  AvailableTagForContractAsArray<TProject, TContract>[number];

type AvailableContractsForTagAsArray<TProject, TTag> =
  TProject extends AccurateProject
    ? TTag extends Tag<TProject>
      ? Projects[TProject]["tags"][TTag]
      : string[]
    : string[];
export type AvailableContractForTag<TProject, TTag> =
  AvailableContractsForTagAsArray<TProject, TTag>[number];

// ##################################################
// ############## ABIS RELATED TYPINGS ##############
// ##################################################

export type AbiForContract<TProject, TTag, TContract> =
  TProject extends keyof ABIs
    ? TTag extends keyof ABIs[TProject]
      ? TContract extends keyof ABIs[TProject][TTag]
        ? ABIs[TProject][TTag][TContract]
        : unknown[]
      : unknown[]
    : unknown[];

// ###################################################
// ############## MAIN UTILITY FUNCTION ##############
// ###################################################

export function project<TProject extends Project>(project: TProject) {
  return {
    /**
     * Get the available tags for the project
     * @returns The array of available tags
     */
    getAvailableTags(): Tag<TProject>[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      if (!(PROJECTS as any)[project]) {
        return [];
      }
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      return Object.keys((PROJECTS as any)[project].tags) as Tag<TProject>[];
    },
    /**
     * Get the available contracts for the project
     * @returns The array of available contracts. Each contract is formatted as "path/to/Contract.sol:Contract"
     */
    getAvailableContracts(): Contract<TProject>[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      if (!(PROJECTS as any)[project]) {
        return [];
      }
      return Object.keys(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (PROJECTS as any)[project].contracts,
      ) as Contract<TProject>[];
    },
    /**
     * Utility functions for a given contract
     * @param contractKey Key of the contract formatted as "path/to/Contract.sol:Contract"
     * @returns Utility functions for the given contract
     * @example ```typescript
     * const counterUtils = project("my-project").contract("src/Counter.sol:Counter");
     * const availableTags = counterUtils.getAvailableTags();
     * const counterArtifact = await counterUtils.getArtifact("v1.3.1");
     * ```
     */
    contract<TContract extends Contract<TProject>>(contractKey: TContract) {
      return {
        getArtifact<TAbi extends unknown[] = unknown[]>(
          tag: AvailableTagForContract<TProject, TContract>,
        ): Promise<EthokoContractArtifact<TAbi>> {
          return getArtifact(
            project,
            tag as string,
            contractKey as string,
          ) as Promise<EthokoContractArtifact<TAbi>>;
        },
        getArtifactSync<TAbi extends unknown[] = unknown[]>(
          tag: AvailableTagForContract<TProject, TContract>,
        ): EthokoContractArtifact<TAbi> {
          return getArtifactSync(
            project,
            tag as string,
            contractKey as string,
          ) as EthokoContractArtifact<TAbi>;
        },
        getAvailableTags(): AvailableTagForContractAsArray<
          TProject,
          TContract
        > {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          if (!(PROJECTS as any)[project]) {
            throw new Error(`Project ${project} not found`);
          }
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          return (PROJECTS as any)[project].contracts[contractKey as string];
        },
      };
    },
    /**
     * Utility functions for a given tag
     * @param tag Tag
     * @returns Utility functions for the given tag
     * @example ```typescript
     * const v1_3_1Utils = project("my-project").tag("v1.3.1");
     * const availableContracts = v1_3_1Utils.getAvailableContracts();
     * const inputCompilationArtifact = await v1_3_1Utils.getInputCompilationArtifact();
     * const contractOutputCompilationArtifact = await v1_3_1Utils.getContractOutputCompilationArtifact("src/IncrementOracle.sol:IncrementOracle");
     * const incrementOracleArtifact = await v1_3_1Utils.getContractArtifact("src/IncrementOracle.sol:IncrementOracle");
     * ```
     */
    tag<TTag extends Tag<TProject>>(tag: TTag) {
      return {
        getContractArtifact<
          TContractKey extends AvailableContractForTag<TProject, TTag>,
        >(
          contractKey: TContractKey,
        ): Promise<
          EthokoContractArtifact<AbiForContract<TProject, TTag, TContractKey>>
        > {
          return getArtifact(
            project,
            tag as string,
            contractKey as string,
          ) as Promise<
            EthokoContractArtifact<AbiForContract<TProject, TTag, TContractKey>>
          >;
        },
        getContractArtifactSync<
          TContractKey extends AvailableContractForTag<TProject, TTag>,
        >(
          contractKey: TContractKey,
        ): EthokoContractArtifact<
          AbiForContract<TProject, TTag, TContractKey>
        > {
          return getArtifactSync(
            project,
            tag as string,
            contractKey as string,
          ) as EthokoContractArtifact<
            AbiForContract<TProject, TTag, TContractKey>
          >;
        },
        getAvailableContracts(): AvailableContractsForTagAsArray<
          TProject,
          TTag
        > {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          if (!(PROJECTS as any)[project]) {
            throw new Error(`Project ${project} not found`);
          }
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          return (PROJECTS as any)[project].tags[tag];
        },
        getInputCompilationArtifact() {
          return getInputCompilationArtifact(project, tag as string);
        },
        getContractOutputCompilationArtifact(
          contractKey: AvailableContractForTag<TProject, TTag>,
        ) {
          return getContractOutputCompilationArtifact(
            project,
            tag as string,
            contractKey as string,
          );
        },
        getInputCompilationArtifactSync() {
          return getInputCompilationArtifactSync(project, tag as string);
        },
        getContractOutputCompilationArtifactSync(
          contractKey: AvailableContractForTag<TProject, TTag>,
        ) {
          return getContractOutputCompilationArtifactSync(
            project,
            tag as string,
            contractKey as string,
          );
        },
      };
    },
  };
}

async function getArtifact<TAbi extends unknown[] = unknown[]>(
  project: string,
  tag: string,
  contractKey: string,
): Promise<EthokoContractArtifact<TAbi>> {
  const contractArtifactResult = await toAsyncResult(
    getContractOutputCompilationArtifact(project, tag, contractKey),
  );
  if (!contractArtifactResult.success) {
    throw contractArtifactResult.error;
  }

  const metadataParsingResult = toResult(
    () =>
      JSON.parse(
        contractArtifactResult.value.output.contract.metadata,
      ) as ContractMetadata,
  );
  if (!metadataParsingResult.success) {
    throw new Error(
      `Failed to parse metadata for contract ${contractKey} in project "${project}:${tag}": ${metadataParsingResult.error}`,
    );
  }
  const expandedMetadata = metadataParsingResult.value;

  const sourcesWithMissingContent = Object.entries(
    metadataParsingResult.value.sources,
  )
    .filter(([, source]) => !source.content)
    .map(([sourcePath]) => sourcePath);

  if (sourcesWithMissingContent.length > 0) {
    const inputArtifactResult = await toAsyncResult(
      getInputCompilationArtifact(project, tag),
    );
    if (!inputArtifactResult.success) {
      throw inputArtifactResult.error;
    }
    const inputArtifact = inputArtifactResult.value;

    for (const sourcePath of sourcesWithMissingContent) {
      const inputSource = inputArtifact.input.sources[sourcePath];
      if (inputSource && inputSource.content) {
        if (!expandedMetadata.sources[sourcePath]) {
          // Unreachable in practice
          continue;
        }
        expandedMetadata.sources[sourcePath].content = inputSource.content;
      }
    }
  }

  return contractOutputArtifactToExportedArtifact(
    project,
    tag,
    contractArtifactResult.value,
    expandedMetadata,
  );
}

function getArtifactSync<TAbi extends unknown[] = unknown[]>(
  project: string,
  tag: string,
  contractKey: string,
): EthokoContractArtifact<TAbi> {
  const contractArtifact = getContractOutputCompilationArtifactSync(
    project,
    tag,
    contractKey,
  );

  const metadataParsingResult = toResult(
    () =>
      JSON.parse(contractArtifact.output.contract.metadata) as ContractMetadata,
  );
  if (!metadataParsingResult.success) {
    throw new Error(
      `Failed to parse metadata for contract ${contractKey} in project "${project}:${tag}": ${metadataParsingResult.error}`,
    );
  }
  const expandedMetadata = metadataParsingResult.value;

  const sourcesWithMissingContent = Object.entries(
    metadataParsingResult.value.sources,
  )
    .filter(([, source]) => !source.content)
    .map(([sourcePath]) => sourcePath);

  if (sourcesWithMissingContent.length > 0) {
    const inputArtifact = getInputCompilationArtifactSync(project, tag);

    for (const sourcePath of sourcesWithMissingContent) {
      const inputSource = inputArtifact.input.sources[sourcePath];
      if (inputSource && inputSource.content) {
        if (!expandedMetadata.sources[sourcePath]) {
          // Unreachable in practice
          continue;
        }
        expandedMetadata.sources[sourcePath].content = inputSource.content;
      }
    }
  }

  return contractOutputArtifactToExportedArtifact(
    project,
    tag,
    contractArtifact,
    expandedMetadata,
  );
}

function contractOutputArtifactToExportedArtifact<
  TAbi extends unknown[] = unknown[],
>(
  project: string,
  tag: string,
  contractArtifact: EthokoOutputContractArtifact,
  expandedMetadata: ContractMetadata,
): EthokoContractArtifact<TAbi> {
  return {
    tag,
    _format: "exported-ethoko-contract-artifact-v0",
    id: contractArtifact.id,
    project,
    abi: contractArtifact.output.contract.abi as TAbi,
    metadata: contractArtifact.output.contract.metadata || "",
    bytecode: prefixWith0x(
      contractArtifact.output.contract.evm.bytecode.object,
    ),
    deployedBytecode: contractArtifact.output.contract.evm.deployedBytecode
      ?.object
      ? prefixWith0x(
          contractArtifact.output.contract.evm.deployedBytecode.object,
        )
      : "0x",
    linkReferences:
      contractArtifact.output.contract.evm.bytecode.linkReferences,
    deployedLinkReferences: contractArtifact.output.contract.evm
      .deployedBytecode
      ? contractArtifact.output.contract.evm.deployedBytecode.linkReferences
      : {},
    contractName: contractArtifact.contract,
    sourceName: contractArtifact.sourceName,
    userdoc: contractArtifact.output.contract.userdoc,
    devdoc: contractArtifact.output.contract.devdoc,
    storageLayout: contractArtifact.output.contract.storageLayout,
    evm: contractArtifact.output.contract.evm,
    expandedMetadata,
  };
}

function prefixWith0x(s: string): `0x${string}` {
  if (s.startsWith("0x")) return s as `0x${string}`;
  return `0x${s}`;
}

/**
 * Get a contract output compilation artifact
 * @param project Related project
 * @param tag Tag of the compilation
 * @param contractKey Key of the contract formatted as "path/to/Contract.sol:Contract"
 * @returns The contract output compilation artifact
 * @throws If the artifact is not found or if the contract key is invalid
 */
async function getContractOutputCompilationArtifact(
  project: string,
  tag: string,
  contractKey: string,
): Promise<EthokoOutputContractArtifact> {
  const manifestPath = `${ETHOKO_PATH}/${project}/tags/${tag}.json`;
  const buildInfoExists = await fs.stat(manifestPath).catch(() => false);
  if (!buildInfoExists) {
    throw new Error(`artifact not found for "${project}:${tag}". Skipping`);
  }
  const manifestContentResult = await toAsyncResult(
    fs.readFile(manifestPath, "utf-8").then(JSON.parse),
  );
  if (!manifestContentResult.success) {
    console.error(manifestContentResult.error);
    throw manifestContentResult.error;
  }
  const manifest = manifestContentResult.value as { id: string };

  const contractPieces = contractKey.split(":");
  const contractName = contractPieces.at(-1);
  if (!contractName) {
    throw new Error(
      `Invalid contract key: ${contractKey}. Expected format: "path/to/Contract.sol:Contract"`,
    );
  }
  const contractPath = contractPieces.at(0);
  if (!contractPath) {
    throw new Error(
      `Invalid contract key: ${contractKey}. Expected format: "path/to/Contract.sol:Contract"`,
    );
  }

  const contractOutputPath = `${ETHOKO_PATH}/${project}/ids/${manifest.id}/outputs/${contractPath}/${contractName}.json`;

  const contractOutputResult = await toAsyncResult(
    fs.readFile(contractOutputPath, "utf-8").then(JSON.parse),
  );

  if (!contractOutputResult.success) {
    console.error(contractOutputResult.error);
    throw contractOutputResult.error;
  }

  return contractOutputResult.value as EthokoOutputContractArtifact;
}

/**
 * Get a contract output compilation artifact
 * @param project Related project
 * @param tag Tag of the compilation
 * @param contractKey Key of the contract formatted as "path/to/Contract.sol:Contract"
 * @returns The contract output compilation artifact
 * @throws If the artifact is not found or if the contract key is invalid
 */
function getContractOutputCompilationArtifactSync(
  project: string,
  tag: string,
  contractKey: string,
): EthokoOutputContractArtifact {
  const manifestPath = `${ETHOKO_PATH}/${project}/tags/${tag}.json`;
  try {
    fsSync.statSync(manifestPath);
  } catch {
    throw new Error(`artifact not found for "${project}:${tag}". Skipping`);
  }
  try {
    const manifestContent = fsSync.readFileSync(manifestPath, "utf-8");
    const manifest = JSON.parse(manifestContent) as { id: string };

    const contractPieces = contractKey.split(":");
    const contractName = contractPieces.at(-1);
    if (!contractName) {
      throw new Error(
        `Invalid contract key: ${contractKey}. Expected format: "path/to/Contract.sol:Contract"`,
      );
    }
    const contractPath = contractPieces.at(0);
    if (!contractPath) {
      throw new Error(
        `Invalid contract key: ${contractKey}. Expected format: "path/to/Contract.sol:Contract"`,
      );
    }

    const contractOutputPath = `${ETHOKO_PATH}/${project}/ids/${manifest.id}/outputs/${contractPath}/${contractName}.json`;

    const contractOutputContent = fsSync.readFileSync(
      contractOutputPath,
      "utf-8",
    );
    const contractOutput = JSON.parse(contractOutputContent);
    return contractOutput as EthokoOutputContractArtifact;
  } catch (e) {
    console.error(e);
    throw e;
  }
}

/**
 * Get a compilation artifact input
 * @param project Related project
 * @param tag Tag of the compilation
 * @returns The compilation artifact input
 */
async function getInputCompilationArtifact(
  project: string,
  tag: string,
): Promise<EthokoInputArtifact> {
  const manifestPath = `${ETHOKO_PATH}/${project}/tags/${tag}.json`;
  const buildInfoExists = await fs.stat(manifestPath).catch(() => false);
  if (!buildInfoExists) {
    throw new Error(`artifact not found for "${project}:${tag}". Skipping`);
  }
  const manifestContentResult = await toAsyncResult(
    fs.readFile(manifestPath, "utf-8").then(JSON.parse),
  );
  if (!manifestContentResult.success) {
    console.error(manifestContentResult.error);
    throw manifestContentResult.error;
  }
  const manifest = manifestContentResult.value as { id: string };

  const inputPath = `${ETHOKO_PATH}/${project}/ids/${manifest.id}/input.json`;

  const inputResult = await toAsyncResult(
    fs.readFile(inputPath, "utf-8").then(JSON.parse),
  );

  if (!inputResult.success) {
    console.error(inputResult.error);
    throw inputResult.error;
  }

  return {
    id: manifest.id,
    _format: inputResult.value._format,
    solcLongVersion: inputResult.value.solcLongVersion,
    origin: inputResult.value.origin,
    input: inputResult.value.input,
  };
}

/**
 * Get a compilation artifact input
 * @param project Related project
 * @param tag Tag of the compilation
 * @returns The compilation artifact input
 */
function getInputCompilationArtifactSync(
  project: string,
  tag: string,
): EthokoInputArtifact {
  try {
    fsSync.statSync(`${ETHOKO_PATH}/${project}/tags/${tag}.json`);
  } catch {
    throw new Error(`artifact not found for "${project}:${tag}". Skipping`);
  }

  try {
    const manifestPath = `${ETHOKO_PATH}/${project}/tags/${tag}.json`;
    const manifestContent = fsSync.readFileSync(manifestPath, "utf-8");
    const manifest = JSON.parse(manifestContent) as { id: string };

    const inputPath = `${ETHOKO_PATH}/${project}/ids/${manifest.id}/input.json`;
    const inputContent = fsSync.readFileSync(inputPath, "utf-8");
    const input = JSON.parse(inputContent);
    return {
      id: manifest.id,
      _format: input._format,
      solcLongVersion: input.solcLongVersion,
      origin: input.origin,
      input: input.input,
    };
  } catch (e) {
    console.error(e);
    throw e;
  }
}

function toAsyncResult<T, TError = Error>(
  promise: Promise<T>,
  opts: {
    debug?: boolean;
  } = {},
): Promise<{ success: true; value: T } | { success: false; error: TError }> {
  return promise
    .then((value) => ({ success: true as const, value }))
    .catch((error) => {
      if (opts.debug) {
        console.error(error);
      }
      return { success: false as const, error };
    });
}

function toResult<T>(
  fn: () => T,
): { success: true; value: T } | { success: false; error: Error } {
  try {
    const value = fn();
    return { success: true, value };
  } catch (error) {
    return { success: false, error: error as Error };
  }
}

// #############################################################
// ##################### Compilation types #####################
// #############################################################

type EthokoArtifactOrigin =
  | {
      type: "forge-v1-default";
      id: string;
    }
  | {
      type: "forge-v1-with-build-info-option";
      id: string;
      format: string;
    }
  | {
      type: "hardhat-v2";
      id: string;
      format: string;
    }
  | {
      type: "hardhat-v3-non-isolated-build";
      id: string;
      pair: {
        inputFormat: string;
        outputFormat: string;
      };
    }
  | {
      type: "hardhat-v3";
      pairs: Array<{
        id: string;
        inputFormat: string;
        outputFormat: string;
      }>;
    };
export interface EthokoInputArtifact {
  id: string;
  _format: "ethoko-input-v0";
  solcLongVersion: string;
  origin: EthokoArtifactOrigin;
  input: CompilerInput;
}
export interface EthokoOutputContractArtifact {
  id: string;
  _format: "ethoko-output-v0";
  sourceName: string;
  contract: string;
  output: {
    contract: CompilerOutputContract;
    source?: CompilerOutputSource;
  };
}

interface CompilerInput {
  language: string;
  sources: { [sourceName: string]: InputSource };
  settings?: InputSettings;
}

interface InputSource {
  license?: string;
  keccak256?: string;
  urls?: string[];
  content?: string;
  ast?: Record<string, unknown>;
  assemblyJson?: {
    ".code": unknown[];
    ".data"?: Record<string, unknown>;
    sourceList?: string[];
  };
}

interface InputSettings {
  stopAfter?: string;
  remappings?: string[];
  optimizer?: OptimizerSettings;
  evmVersion?: string;
  eofVersion?: number;
  viaIr?: boolean;
  debug?: unknown;
  metadata?: unknown;
  libraries?: Record<string, Record<string, string>>;
  outputSelection?: unknown;
  modelChecker?: unknown;
}
interface OptimizerSettings {
  enabled?: boolean;
  runs?: number;
  details?: unknown;
}

interface CompilerOutputSource {
  id: number;
  ast: unknown;
}

interface CompilerOutputContract {
  abi: unknown[];
  metadata: string;
  userdoc?: unknown;
  devdoc?: unknown;
  ir?: string;
  irAst?: unknown;
  irOptimized?: string;
  irOptimizedAst?: unknown;
  storageLayout?: unknown;
  transientStorageLayout?: unknown;
  evm: {
    assembly?: string;
    legacyAssembly?: unknown;
    bytecode: CompilerOutputBytecode;
    deployedBytecode?: CompilerOutputBytecode & {
      immutableReferences?: unknown;
    };
    methodIdentifiers?: {
      [methodSignature: string]: string;
    };
    gasEstimates?: {
      creation?: Record<string, string>;
      external?: Record<string, string>;
      internal?: Record<string, string>;
    } | null;
  };
}

interface CompilerOutputBytecode {
  functionDebugData?: unknown;
  object: string;
  opcodes?: string;
  sourceMap?: string;
  generatedSources?: unknown[];
  linkReferences: LinkReferences;
}

interface LinkReferences {
  [libraryFileName: string]: {
    [libraryName: string]: Array<{ length: number; start: number }>;
  };
}

interface ContractMetadata {
  compiler: {
    keccak256?: string;
    version: string;
  };
  language: string;
  output: {
    abi: unknown[];
    devdoc?: unknown;
    userdoc?: unknown;
  };
  settings: {
    remappings?: string[];
    optimizer?: OptimizerSettings;
    evmVersion?: string;
    eofVersion?: number;
    viaIr?: boolean;
    metadata?: unknown;
    modelChecker?: unknown;
    libraries?: Record<string, string>;
    compilationTarget?: Record<string, string>;
  };
  sources: Record<
    string,
    {
      license?: string;
      keccak256?: string;
      urls?: string[];
      content?: string;
    }
  >;
  version: number;
}

/**
 * This interface is derived from the compilation output.
 *
 * It is meant to integrate in a smoother way with external dependencies.
 */
export interface EthokoContractArtifact<
  TAbi extends readonly unknown[] = readonly unknown[],
> {
  /**
   * Tag of the artifact, null if the artifact was retrieved using an ID instead of a tag
   */
  readonly tag: string | null;
  /**
   * Format, hardcoded to `exported-ethoko-contract-artifact-v0` for now
   */
  readonly _format: "exported-ethoko-contract-artifact-v0";
  /**
   * Ethoko artifact ID
   */
  readonly id: string;
  /**
   * Ethoko project name
   */
  readonly project: string;
  /**
   * ABI of the artifact
   */
  readonly abi: TAbi;
  /**
   * Metadata of the artifact, fallback to empty string
   */
  readonly metadata: string;
  /**
   * Bytecode formatted with `0x` prefix
   */
  readonly bytecode: `0x${string}`;
  /**
   * Deployed bytecode, formatted with `0x` prefix, fallback to `0x`
   */
  readonly deployedBytecode: `0x${string}`;
  /**
   * Link references for the libraries
   */
  readonly linkReferences: LinkReferences;
  /**
   * Link references for the deployed libraries, fallback to empty object
   */
  readonly deployedLinkReferences: LinkReferences;
  /**
   * Name of the contract
   */
  readonly contractName: string;
  /**
   * Relative path
   */
  readonly sourceName: string;
  /**
   * User documentation
   */
  readonly userdoc?: unknown;
  /**
   * Dev documentation
   */
  readonly devdoc?: unknown;
  /**
   * Storage layout
   */
  readonly storageLayout?: unknown;
  /**
   * Full EVM compilation output object
   */
  readonly evm: {
    readonly assembly?: string;
    readonly bytecode: CompilerOutputBytecode;
    readonly deployedBytecode?: CompilerOutputBytecode;
    readonly gasEstimates?: {
      readonly creation?: Record<string, string>;
      readonly external?: Record<string, string>;
      readonly internal?: Record<string, string>;
    } | null;
    readonly methodIdentifiers?: {
      readonly [methodSignature: string]: string;
    };
  };
  /**
   * Expanded metadata, parsed from the "metadata" field of the contract output.
   * If the `content` field of the sources in the metadata is missing, it will try to fill it with the content from the input compilation artifact if it can find a match based on the source name.
   * However, if it cannot find a match, the `content` field will be left as is (potentially undefined).
   */
  expandedMetadata: ContractMetadata;
}
