import fs from "fs/promises";
import path from "path";
import { createInterface } from "node:readline/promises";
import { styleText } from "util";
import { LOG_COLORS } from "@/ui/utils";
import { toAsyncResult } from "@/utils/result";
import { CliError } from "../error";
import {
  inferOriginalArtifactFormat,
  InferredArtifact,
} from "@/supported-origins/infer-original-artifact-format";
import { OriginalBuildInfoPaths } from "@/supported-origins/map-original-artifact-to-ethoko-artifact";

type CandidateBuildInfoOption = {
  display: string;
  value: OriginalBuildInfoPaths;
};

/**
 * Given the input path, look for candidate compilation artifacts (build info).
 *
 * This function is meant to be used in other CLI client methods, since it throws a CliError, it can be used without any wrapping, i.e.
 * ```ts
 * const buildInfoPath = await lookForBuildInfo(inputPath);
 * ```
 *
 * The goal is to support multiple providers of compilation artifacts, which may have different formats and structures.
 * The different supported formats are:
 * - Hardhat v2: a single JSON file containing both the input and output of the compilation, in the format generated by Hardhat v2, contained in the `build-info` directory of the Hardhat project by default
 * - Hardhat v3: muliple pairs of JSON files, one for the input of the compilation and one for the output, in the format generated by Hardhat v3, contained in the `build-info` directory of the Hardhat project by default. The input and output files are linked by a common id field in their content. A pair is emitted for each contract.
 * - Forge (default compilation mode): a single JSON file containing only an ID and references to the actual contract artifacts.
 * - Forge (with build info option): a single JSON file containing both the input and output of the compilation, in a format that is similar to Hardhat v2 but with some differences, emitted when using the `--build-info` option of Forge.
 *
 * The strategy is the following:
 * - If the inputPath is directly a JSON file:
 *  - we infer the format of the file based on its content,
 *  - if the format is recognized as a supported build info format, we return it. In case of Hardhat v3, we rebuild the pair of input/output files based on the common id field and return both paths, we don't look for other pairs.
 * - if the inputPath is a directory, we look for a `build-info` directory:
 *  - if it exists, we consider it as the main candidate to look for JSON files,
 *  - if it doesn't exist, we look for JSON files directly in the inputPath directory.
 * - for each JSON file found, we infer its format based on its content,
 * - from the inferred formats, we build the list of valid options:
 *  - Hardhat v2, Forge (default) and Forge (with build info option) files are valid on their own,
 *  - for Hardhat v3,
 *    - we gather the pairs,
 *    - we gather the pairs with the same Solc version and with creation window close (2 minutes, based on the mtime of the files) since they are more likely to be related to the same compilation,
 *    - an option is created for each of these set of pairs, with a display name containing the Solc version and the mtime of the files for the user to differentiate them.
 * The list of options is returned to the caller, as well as the count of ignored files (files that are not recognized as valid build info files) and the final folder path where the files are located (either the inputPath or the build-info directory if it exists).
 * @param inputPath The path to look for the build info JSON file
 * @param opts Options for the function
 * @param opts.debug Enable debug mode
 * @returns An object containing the candidate artifact options, the count of ignored files, and the final folder path
 * @throws A CliError
 */
export async function lookForCandidateArtifacts(
  inputPath: string,
  opts: { debug: boolean },
): Promise<{
  candidateBuildInfoOptions: CandidateBuildInfoOption[];
  ignoredFilesCount: number;
  finalFolderPath: string;
}> {
  const { debug } = opts;
  const statResult = await toAsyncResult(fs.stat(inputPath), { debug });
  if (!statResult.success) {
    throw new CliError(
      `The provided path "${inputPath}" does not exist or is not accessible. Please provide a valid path to a compilation artifact (build info) or a directory containing it.`,
    );
  }

  // The provided path is a file, we check if it is a valid JSON file and if it is in a supported format
  if (statResult.value.isFile()) {
    if (!inputPath.endsWith(".json")) {
      throw new CliError(
        `The provided path "${inputPath}" is a file but does not have a .json extension. Please provide a valid path to a JSON compilation artifact (build info).`,
      );
    }
    const contentResult = await toAsyncResult(
      fs.readFile(inputPath, "utf-8").then((v) => JSON.parse(v)),
      { debug },
    );
    if (!contentResult.success) {
      throw new CliError(
        `The provided file "${inputPath}" could not be read or is not a valid JSON file. Please check the file and try again. Run with debug mode for more info.`,
      );
    }

    const format = inferOriginalArtifactFormat(contentResult.value);
    if (!format.recognized) {
      throw new CliError(
        `The provided file "${inputPath}" does not seem to be a valid build info JSON file in a supported format. Please provide a valid build info JSON file. Run with debug mode for more info.`,
      );
    }
    if (
      format.artifact.format === "hardhat-v3-input-isolated-build" ||
      format.artifact.format === "hardhat-v3-input-no-isolated-build"
    ) {
      // We verify that the corresponding output file exists
      const matchingOutputPath = inputPath.replace(".json", ".output.json");
      const outputCheckResult = await toAsyncResult(
        fs
          .stat(matchingOutputPath)
          .then(() => fs.readFile(matchingOutputPath, "utf-8"))
          .then(JSON.parse)
          .then((json) => {
            const inferredFormat = inferOriginalArtifactFormat(json);
            if (
              !inferredFormat.recognized ||
              inferredFormat.artifact.format !== "hardhat-v3-output"
            ) {
              throw new Error(
                "Output file does not seem to be in hardhat v3 output format",
              );
            }
          }),
        { debug },
      );
      if (!outputCheckResult.success) {
        throw new CliError(
          `The provided file "${inputPath}" seems to be in Hardhat V3 input format, but the corresponding output file "${matchingOutputPath}" is missing or not valid. Please make sure both files are present and valid. Run with debug mode for more info.`,
        );
      }
      return {
        finalFolderPath: path.dirname(inputPath),
        ignoredFilesCount: 0,
        candidateBuildInfoOptions: [
          {
            display: "Input build info",
            value: {
              format: "hardhat-v3",
              buildInfoPaths: [
                { input: inputPath, output: matchingOutputPath },
              ],
            },
          },
        ],
      };
    }
    if (format.artifact.format === "hardhat-v3-output") {
      // We verify that the corresponding input file exists
      const matchingInputPath = inputPath.replace(".output.json", ".json");
      const inputCheckResult = await toAsyncResult(
        fs
          .stat(matchingInputPath)
          .then(() => fs.readFile(matchingInputPath, "utf-8"))
          .then(JSON.parse)
          .then((json) => {
            const inferredFormat = inferOriginalArtifactFormat(json);
            if (
              !inferredFormat.recognized ||
              (inferredFormat.artifact.format !==
                "hardhat-v3-input-isolated-build" &&
                inferredFormat.artifact.format !==
                  "hardhat-v3-input-no-isolated-build")
            ) {
              throw new Error(
                "Input file does not seem to be in hardhat v3 input format",
              );
            }
          }),
        { debug },
      );
      if (!inputCheckResult.success) {
        throw new CliError(
          `The provided file "${inputPath}" seems to be in Hardhat V3 output format, but the corresponding input file "${matchingInputPath}" is missing or not valid. Please make sure both files are present and valid. Run with debug mode for more info.`,
        );
      }
      return {
        finalFolderPath: path.dirname(inputPath),
        ignoredFilesCount: 0,
        candidateBuildInfoOptions: [
          {
            display: "Input build info",
            value: {
              format: "hardhat-v3",
              buildInfoPaths: [{ input: matchingInputPath, output: inputPath }],
            },
          },
        ],
      };
    }

    return {
      finalFolderPath: path.dirname(inputPath),
      ignoredFilesCount: 0,
      candidateBuildInfoOptions: [
        {
          display: "Input build info",
          value: {
            buildInfoPath: inputPath,
            format: format.artifact.format,
          },
        },
      ],
    };
  }

  if (!statResult.value.isDirectory()) {
    throw new CliError(
      `The provided path "${inputPath}" is neither a file nor a directory. Please provide a valid path to a compilation artifact (build info) or a directory containing it.`,
    );
  }

  // We look for the directory and the entries we're gonna work with:
  // - if there is a `build-info` directory, we look for JSON files in it and consider it as the main candidate,
  // - if there is no `build-info` directory, we look for JSON files directly in the provided directory
  const entriesResult = await toAsyncResult(
    fs.readdir(inputPath, { withFileTypes: true }),
    {
      debug,
    },
  );
  if (!entriesResult.success) {
    throw new CliError(
      `The provided path "${inputPath}" is a directory but could not be read. Please check the permissions and try again. Run with debug mode for more info.`,
    );
  }

  let finalEntries = entriesResult.value;
  let finalFolderPath = inputPath;

  const buildInfoDirEntry = entriesResult.value.find(
    (entry) => entry.isDirectory() && entry.name === "build-info",
  );
  if (buildInfoDirEntry) {
    const buildInfoDirPath = `${inputPath}/build-info`;
    const buildInfoEntriesResult = await toAsyncResult(
      fs.readdir(buildInfoDirPath, { withFileTypes: true }),
      { debug },
    );
    if (!buildInfoEntriesResult.success) {
      throw new CliError(
        `The "build-info" directory in the provided path "${inputPath}" could not be read. Please check the permissions and try again. Run with debug mode for more info.`,
      );
    }
    finalFolderPath = buildInfoDirPath;
    finalEntries = buildInfoEntriesResult.value;
  }

  // We consider the JSON files
  const jsonFiles = finalEntries.filter(
    (entry) => entry.isFile() && entry.name.endsWith(".json"),
  );

  const jsonFilesWithStats: (
    | { ignored: false; summary: FileSummary }
    | { ignored: true; name: string }
  )[] = await Promise.all(
    jsonFiles.map(async (file) => {
      const filePath = `${finalFolderPath}/${file.name}`;
      const statsResult = await toAsyncResult(fs.stat(filePath), {
        debug,
      });
      if (!statsResult.success) {
        if (debug) {
          console.error(
            `Failed to get stats for file "${filePath}". Error: ${statsResult.error}`,
          );
        }
        return {
          ignored: true as const,
          name: file.name,
        };
      }

      const inferrenceResult = await toAsyncResult(
        fs
          .readFile(filePath, "utf-8")
          .then((v) => JSON.parse(v))
          .then(inferOriginalArtifactFormat),
        { debug },
      );
      if (!inferrenceResult.success) {
        if (debug) {
          console.error(
            `Failed to infer format for file "${filePath}". Error: ${inferrenceResult.error}`,
          );
        }
        return {
          ignored: true as const,
          name: file.name,
        };
      }
      if (!inferrenceResult.value.recognized) {
        if (debug) {
          console.error(
            `File "${filePath}" is not a valid build info JSON file (format inferred as "unknown"). It will be ignored.`,
          );
        }
        return {
          ignored: true as const,
          name: file.name,
        };
      }

      return {
        ignored: false as const,
        summary: {
          name: file.name,
          filePath,
          mtime: statsResult.value.mtime,
          size: statsResult.value.size,
          artifact: inferrenceResult.value.artifact,
        } satisfies FileSummary,
      };
    }),
  );

  let ignoredFilesCount = 0;
  const files: FileSummary[] = [];
  for (const file of jsonFilesWithStats) {
    if (file.ignored) {
      ignoredFilesCount++;
      continue;
    }
    files.push(file.summary);
  }

  files.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

  return {
    candidateBuildInfoOptions: filesToOptions(files),
    ignoredFilesCount,
    finalFolderPath,
  };
}

type FileSummary = {
  name: string;
  filePath: string;
  mtime: Date;
  size: number;
  artifact: InferredArtifact;
};
function filesToOptions(files: FileSummary[]): CandidateBuildInfoOption[] {
  const options: CandidateBuildInfoOption[] = [];
  const hardhatV3Pairs: {
    input: {
      path: string;
      size: number;
    };
    output: {
      path: string;
      size: number;
    };
    solcLongVersion: string;
    id: string;
    mtime: Date;
  }[] = [];
  for (const file of files) {
    if (file.artifact.format === "hardhat-v3-input-no-isolated-build") {
      const hardhatV3BuildInfoId = file.artifact.data.id;
      // We check if the corresponding output file is present in the list of files, if not, we ignore this file since it is not a valid build info on its own
      const matchingOutputFile = files.find(
        (f) =>
          f.artifact.format === "hardhat-v3-output" &&
          f.artifact.data.id === hardhatV3BuildInfoId,
      );
      if (!matchingOutputFile) {
        continue;
      }
      options.push({
        display: `${truncateFilename(file.name)} (Hardhat v3, Solc ${file.artifact.data.solcLongVersion}, ${formatTimeAgo(file.mtime)})`,
        value: {
          format: "hardhat-v3-non-isolated-build",
          buildInfoPaths: {
            input: file.filePath,
            output: matchingOutputFile.filePath,
          },
        },
      });
    } else if (file.artifact.format === "hardhat-v3-input-isolated-build") {
      const hardhatV3BuildInfoId = file.artifact.data.id;
      // We check if the corresponding output file is present in the list of files, if not, we ignore this file since it is not a valid build info on its own
      const matchingOutputFile = files.find(
        (f) =>
          f.artifact.format === "hardhat-v3-output" &&
          f.artifact.data.id === hardhatV3BuildInfoId,
      );
      if (!matchingOutputFile) {
        continue;
      }
      hardhatV3Pairs.push({
        solcLongVersion: file.artifact.data.solcLongVersion,
        id: hardhatV3BuildInfoId,
        mtime: file.mtime,
        input: {
          path: file.filePath,
          size: file.size,
        },
        output: {
          path: matchingOutputFile.filePath,
          size: matchingOutputFile.size,
        },
      });
    } else if (file.artifact.format === "hardhat-v3-output") {
      // Hardhat V3 output files are ignored as they will be handled together with their corresponding input file
    } else {
      options.push({
        display: `${truncateFilename(file.name)} (${BUILD_INFO_FORMAT_TO_HUMAN_READABLE[file.artifact.format]}, ${formatTimeAgo(file.mtime)}, ${formatFileSize(file.size)})`,
        value: {
          buildInfoPath: file.filePath,
          format: file.artifact.format,
        },
      });
    }
  }

  // We group the Hardhat V3 pairs by Solc version and with creation window close (2 minutes) since they are more likely to be related to the same compilation, and we create an option for each of these groups
  hardhatV3Pairs.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());
  const hardhatV3PairsGroups: {
    solcLongVersion: string;
    startWindow: Date;
    pairs: typeof hardhatV3Pairs;
  }[] = [];
  for (const pair of hardhatV3Pairs) {
    const existingGroup = hardhatV3PairsGroups.find(
      (group) =>
        group.solcLongVersion === pair.solcLongVersion &&
        Math.abs(group.startWindow.getTime() - pair.mtime.getTime()) <=
          2 * 60 * 1000,
    );
    if (existingGroup) {
      existingGroup.pairs.push(pair);
    } else {
      hardhatV3PairsGroups.push({
        solcLongVersion: pair.solcLongVersion,
        startWindow: pair.mtime,
        pairs: [pair],
      });
    }
  }
  const hardhatV3OptionGroups: CandidateBuildInfoOption[] =
    hardhatV3PairsGroups.map((group) => {
      const display = `${BUILD_INFO_FORMAT_TO_HUMAN_READABLE["hardhat-v3"]} (Solc ${group.solcLongVersion}, ${formatTimeAgo(group.startWindow)}`;
      const value: OriginalBuildInfoPaths = {
        format: "hardhat-v3",
        buildInfoPaths: group.pairs.map((pair) => ({
          input: pair.input.path,
          output: pair.output.path,
        })),
      };
      return {
        display,
        value,
      };
    });

  options.push(...hardhatV3OptionGroups);

  return options;
}

/**
 * Prompts the user to select one option from a list
 * @param message The message to display to the user
 * @param options The list of options to choose from
 * @param timeoutMs Optional timeout in milliseconds (default: 30000ms = 30s). Set to 0 to disable timeout.
 * @returns The selected option
 * @throws CliError when timeout is reached
 */
export async function promptUserSelection(
  message: string,
  options: CandidateBuildInfoOption[],
  timeoutMs: number = 30_000,
): Promise<OriginalBuildInfoPaths> {
  const readline = createInterface({
    input: process.stdin,
    output: process.stderr,
  });

  let timeoutId: NodeJS.Timeout | null = null;
  let isTimedOut = false;
  let isClosed = false;

  const timeoutPromise =
    timeoutMs > 0
      ? new Promise<never>((_, reject) => {
          timeoutId = setTimeout(() => {
            isTimedOut = true;
            if (!isClosed) {
              isClosed = true;
              readline.close();
            }
            reject(
              new CliError(
                `User selection timed out after ${timeoutMs / 1_000}s.`,
              ),
            );
          }, timeoutMs);
        })
      : new Promise<never>(() => {}); // Never resolves if timeout is disabled

  async function selectionPromise() {
    console.error("");
    console.error(styleText(LOG_COLORS.log, message));
    options.forEach((option, index) => {
      console.error(
        styleText(LOG_COLORS.log, `  ${index + 1}. ${option.display}`),
      );
    });
    console.error("");

    let selectedIndex: number | null = null;
    let warningLinesCount = 0;
    let promptLinesCount = 0;

    while (selectedIndex === null && !isTimedOut) {
      promptLinesCount++;
      const answer = await readline.question(
        styleText(LOG_COLORS.log, "Enter your choice (number): "),
      );

      const parsed = parseInt(answer.trim(), 10);

      if (isNaN(parsed) || parsed < 1 || parsed > options.length) {
        console.error(
          styleText(
            LOG_COLORS.warn,
            `⚠️  Invalid selection. Please enter a number between 1 and ${options.length}`,
          ),
        );
        warningLinesCount++;
      } else {
        selectedIndex = parsed - 1;
      }
    }

    if (timeoutId) {
      clearTimeout(timeoutId);
    }
    if (!isClosed) {
      isClosed = true;
      readline.close();
    }

    const baseLinesCount = 2 + options.length + 1;
    const linesToClear = baseLinesCount + promptLinesCount + warningLinesCount;

    for (let i = 0; i < linesToClear; i++) {
      process.stderr.write("\x1b[1A");
      process.stderr.write("\x1b[2K");
    }
    process.stderr.write("\r");

    if (selectedIndex === null) {
      throw new Error("Selection was interrupted");
    }

    const selected = options[selectedIndex];
    if (!selected) {
      throw new Error(
        `Failed to get selected option at index ${selectedIndex}`,
      );
    }

    return selected.value;
  }

  return await Promise.race([selectionPromise(), timeoutPromise]).catch(
    (error) => {
      if (timeoutId) {
        clearTimeout(timeoutId);
      }
      if (!isClosed) {
        isClosed = true;
        readline.close();
      }
      throw error;
    },
  );
}

function formatTimeAgo(date: Date): string {
  const now = new Date();
  const diff = now.getTime() - date.getTime();
  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);

  if (days > 0) return `${days}d ago`;
  if (hours > 0) return `${hours}h ago`;
  if (minutes > 0) return `${minutes}m ago`;
  return "just now";
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)}MB`;
}

function truncateFilename(filename: string, maxLength: number = 60): string {
  if (filename.length <= maxLength) return filename;

  const dotIndex = filename.lastIndexOf(".");
  if (dotIndex <= 0 || dotIndex === filename.length - 1) {
    return `${filename.slice(0, Math.max(1, maxLength - 3))}...`;
  }

  const extension = filename.slice(dotIndex);
  const baseMaxLength = Math.max(1, maxLength - extension.length - 3);
  const base = filename.slice(0, baseMaxLength);
  return `${base}...${extension}`;
}

const BUILD_INFO_FORMAT_TO_HUMAN_READABLE: Record<
  OriginalBuildInfoPaths["format"],
  string
> = {
  "hardhat-v2": "Hardhat v2",
  "hardhat-v3": "Hardhat v3",
  "hardhat-v3-non-isolated-build": "Hardhat v3 (Non isolated build)",
  "forge-v1-default": "Forge",
  "forge-v1-with-build-info-option": "Forge",
};
