// THIS IS AN AUTOGENERATED FILE. EDIT AT YOUR OWN RISKS.

export const ETHOKO_PATH=".ethoko";

export const PROJECTS = {
  "doubtful-counter": {
    contracts: {
      "src/Counter.sol:Counter": ["v1.0.1"],
      "src/IncrementOracle.sol:IncrementOracle": ["v1.0.1"],
    },
    tags: {
      "v1.0.1": ["src/Counter.sol:Counter","src/IncrementOracle.sol:IncrementOracle"],
    },
  },
} as const;
