import { deployScript } from "../rocketh/deploy.js";
import {
  ContractArtifact as EthokoContractArtifact,
  project,
} from "../.ethoko-typings";
import * as RockethTypes from "rocketh/types";

/**
 * This deployment script deploys the Counter contract targeting a specific release.
 *
 * The compilation artifacts are retrieved from the Ethoko project registry for the specified release.
 * The artifacts are **frozen** at the time of the release, ensuring consistent deployments.
 * Local modifications to the contract source code or any new compilation, releases etc.. will not affect this deployment.
 *
 * The `Counter` contract is deployed first.
 * The deployment is done using `hardhat-deploy@v2`.
 *
 * This script relies on typings generated by Ethoko for the project "curious-counter".
 * It is assumed that the tag `2026-02-02` exists in the Ethoko registry for this project.
 * It could have been created by running:
 * ```
 * npx hardhat ethoko push --tag 2026-02-02 --artifact-path ./artifacts
 * ```
 * The assumed commands that have been run prior to this deployment are:
 *  - `npx hardhat ethoko pull` to pull the project from the Ethoko registry,
 *  - `npx hardhat ethoko typings` to generate the typings for the project.
 */

const TARGET_RELEASE_TAG = "2026-02-02";

export default deployScript(
  async ({ deploy, namedAccounts }) => {
    const { deployer } = namedAccounts;

    const projectUtils = project("curious-counter");

    const counterArtifact = await projectUtils
      .tag(TARGET_RELEASE_TAG)
      .getContractArtifact("project/contracts/Counter.sol:Counter");

    await deploy(`Counter@${TARGET_RELEASE_TAG}`, {
      account: deployer,
      // Ethoko still needs refinement on types
      // we use a dedicated function to cast to expected Rocketh's type
      artifact: toRockethArtifact(counterArtifact),
    });
  },
  { tags: ["Counter", "Counter_deploy", TARGET_RELEASE_TAG] },
);

function toRockethArtifact(
  artifact: EthokoContractArtifact,
): RockethTypes.Artifact {
  return {
    abi: artifact.abi as RockethTypes.Abi,
    bytecode: artifact.bytecode,
    metadata: artifact.metadata,
    // | | | | | | | | | | | | | |
    // | | | Optional fields | | |
    // v v v                 v v v
    deployedBytecode: artifact.deployedBytecode,
    linkReferences: artifact.linkReferences,
    deployedLinkReferences: artifact.deployedLinkReferences,
    contractName: artifact.contractName,
    sourceName: artifact.sourceName,
    devdoc: artifact.devdoc as RockethTypes.DevDoc | undefined,
    evm: artifact.evm,
    storageLayout: artifact.storageLayout as
      | RockethTypes.StorageLayout
      | undefined,
    userdoc: artifact.userdoc as RockethTypes.UserDoc | undefined,
  };
}
