import { deployScript } from "../rocketh/deploy.js";
import { project } from "../.ethoko-typings/index.js";
import type * as RockethTypes from "rocketh/types";

/**
 * This deployment script deploys the Counter contract targeting a specific release.
 *
 * The compilation artifacts are retrieved from the Ethoko project registry for the specified release.
 * The artifacts are **frozen** at the time of the release, ensuring consistent deployments.
 * Local modifications to the contract source code or any new compilation, releases etc.. will not affect this deployment.
 *
 * The `Counter` contract is deployed first.
 * The deployment is done using `hardhat-deploy@v2`.
 *
 * This script relies on typings generated by Ethoko for the project "curious-counter".
 * It is assumed that the tag `2026-02-02` exists in the Ethoko registry for this project.
 * It could have been created by running:
 * ```
 * npx ethoko push curious-counter:2026-02-02 --artifact-path ./artifacts
 * ```
 * The assumed commands that have been run prior to this deployment are:
 *  - `npx ethoko pull curious-counter:2026-02-02` to pull the project from the Ethoko registry,
 *  - `npx ethoko typings curious-counter:2026-02-02` to generate the typings for the project.
 */

const TARGET_RELEASE_TAG = "2026-02-02";

export default deployScript(
  async ({ deploy, namedAccounts }) => {
    const { deployer } = namedAccounts;

    const projectUtils = project("curious-counter");

    const counterArtifact = await projectUtils
      .tag(TARGET_RELEASE_TAG)
      .getContractArtifact("project/contracts/Counter.sol:Counter");

    await deploy(`Counter@${TARGET_RELEASE_TAG}`, {
      account: deployer,
      artifact: {
        abi: scopeAbi(counterArtifact.abi),
        bytecode: counterArtifact.bytecode,
        metadata: counterArtifact.metadata,
        // | | | | | | | | | | | | | |
        // | | | Optional fields | | |
        // v v v                 v v v
        deployedBytecode: counterArtifact.deployedBytecode,
        linkReferences: counterArtifact.linkReferences,
        deployedLinkReferences: counterArtifact.deployedLinkReferences,
        contractName: counterArtifact.contractName,
        sourceName: counterArtifact.sourceName,
        devdoc: counterArtifact.devdoc as RockethTypes.DevDoc | undefined,
        evm: counterArtifact.evm,
        storageLayout: counterArtifact.storageLayout as
          | RockethTypes.StorageLayout
          | undefined,
        userdoc: counterArtifact.userdoc as RockethTypes.UserDoc | undefined,
      },
    });
  },
  { tags: ["Counter", "Counter_deploy", TARGET_RELEASE_TAG] },
);

// Scoping method in order to handle the case of empty typings have been generated, e.g. in CI
function scopeAbi<T>(
  abi: T,
): T extends RockethTypes.Abi ? T : RockethTypes.Abi {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return abi as any;
}
