import { deployScript } from "../rocketh/deploy.js";
import { project } from "../.ethoko-typings"

/**
 * This deployment script deploys the Counter contract targeting a specific release.
 *
 * The compilation artifacts are retrieved from the Ethoko project registry for the specified release.
 * The artifacts are **frozen** at the time of the release, ensuring consistent deployments.
 * Local modifications to the contract source code or any new compilation, releases etc.. will not affect this deployment.
 *
 * The `Counter` contract is deployed first.
 * The deployment is done using `hardhat-deploy@v2`.
 *
 * This script relies on typings generated by Ethoko for the project "curious-counter".
 * It is assumed that the tag `2026-02-02` exists in the Ethoko registry for this project.
 * It could have been created by running:
 * ```
 * npx hardhat soko push --tag 2026-02-02 --artifact-path ./artifacts
 * ```
 * The assumed commands that have been run prior to this deployment are:
 *  - `npx hardhat soko pull` to pull the project from the Ethoko registry,
 *  - `npx hardhat soko typings` to generate the typings for the project.
 */

const TARGET_RELEASE_TAG = "2026-02-02";

export default deployScript(
  async ({ deploy, namedAccounts }) => {
    const { deployer } = namedAccounts;

    const projectUtils = project("curious-counter")

    const counterArtifact = await projectUtils.tag(TARGET_RELEASE_TAG).getContractArtifact("project/contracts/Counter.sol:Counter")

    const metadata = counterArtifact.metadata;
    if (!metadata) {
      throw new Error("Metadata is required for deployment, but was not found in the artifact");
    }

    await deploy(`Counter@${TARGET_RELEASE_TAG}`, {
      account: deployer,
      artifact: {
        // Hardhat Deploy works with the abitype dependency, strongly typing the ABI. It is not yet available here.
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        abi: counterArtifact.abi as any,
        bytecode: `0x${counterArtifact.evm.bytecode.object}`,
        metadata
      },
    });
  },
  { tags: ["Counter", "Counter_deploy", TARGET_RELEASE_TAG] },
);

