import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";
import { project } from "../../.ethoko-typings";

/**
 * This deployment script deploys the Counter contract targeting a specific release.
 *
 * The compilation artifacts are retrieved from the Ethoko project registry for the specified release.
 * The artifacts are **frozen** at the time of the release, ensuring consistent deployments.
 * Local modifications to the contract source code or any new compilation, releases etc.. will not affect this deployment.
 *
 * The `Counter` contract is deployed first.
 * The deployment is done using `Hardhat Ignition`.
 *
 * This script relies on typings generated by Ethoko for the project "ignited-counter".
 * It is assumed that the tag `2026-02-02` exists in the Ethoko registry for this project.
 * It could have been created by running:
 * ```
 * npx hardhat ethoko push --tag 2026-02-02
 * ```
 * The assumed commands that have been run prior to this deployment are:
 *  - `npx hardhat ethoko pull` to pull the project from the Ethoko registry,
 *  - `npx hardhat ethoko typings` to generate the typings for the project.
 */

const TARGET_RELEASE_TAG = "2026-02-02";
// Hardhat Ignition likes alphanumeric and underscores
const MODULE_SUFFIX = TARGET_RELEASE_TAG.replaceAll("-", "_");

export default buildModule(`CounterModule_${MODULE_SUFFIX}`, (m) => {
  const projectUtils = project("ignited-counter");

  const counterArtifact = projectUtils
    .tag("2026-02-02")
    .getContractArtifactSync("project/contracts/Counter.sol:Counter");

  const counter = m.contract("Counter", {
    _format: "hh3-artifact-1",
    contractName: "Counter",
    sourceName: "contracts/Counter.sol",
    bytecode: `0x${counterArtifact.evm.bytecode.object}`,
    deployedBytecode: `0x${counterArtifact.evm.deployedBytecode?.object}`,
    linkReferences: counterArtifact.evm.bytecode.linkReferences,
    deployedLinkReferences:
      counterArtifact.evm.deployedBytecode?.linkReferences ?? {},
    abi: counterArtifact.abi,
  });

  m.call(counter, "incBy", [5n]);

  return { counter };
});
