import z from "zod";
import { SolcJsonInputSchema } from "../solc-artifacts-schemas/v0.8.33/input-json";
import {
  OutputSourceSchema,
  SolcContractSchema,
  SolcJsonOutputSchema,
} from "../solc-artifacts-schemas/v0.8.33/output-json";
import { FORGE_COMPILER_OUTPUT_WITH_BUILD_INFO_OPTION_FORMAT } from "../supported-origins/forge-v1/schemas";
import { HARDHAT_V2_COMPILER_OUTPUT_FORMAT } from "../supported-origins/hardhat-v2/schemas";
import {
  HARDHAT_V3_COMPILER_OUTPUT_FORMAT,
  HARDHAT_V3_COMPILER_INPUT_FORMAT,
} from "../supported-origins/hardhat-v3/schemas";

/**
 * Ethoko artifact architectural overview:
 * An Ethoko artifact is composed of multiple parts, split in two main categories:
 * - a unique input artifact, which contains all the information related to the compilation input and metadata (compiler version, optimization settings, etc.).
 *   It also contains the origin of the artifact, which is a structured information about how the artifact was generated (e.g. forge with default settings, hardhat with specific plugins, etc.)
 *   The input artifact uniquely identifies a compilation process. An ID is derived from the content of the input artifact and is used to link it to the output artifact.
 *   // REMIND ME: Add maps of path -> contract?
 *   The input artifact contains the full input JSON as accepted by the Solidity compiler (solc).
 * - many output artifacts, one for each contract, which contains the output of the compilation process for that specific contract.
 *   It contains the ID of the input artifact it is linked to, and the output JSON as generated by the Solidity compiler (solc) but only for that specific contract.
 *   Outputs for imported contracts or libraries are not included in this output artifact but will be found in their own output artifacts.
 */

const EthokoArtifactOriginSchema = z.discriminatedUnion("type", [
  z.object({
    id: z.string(),
    type: z.literal("forge-v1-default"),
  }),
  z.object({
    id: z.string(),
    type: z.literal("forge-v1-with-build-info-option"),
    format: z.literal(FORGE_COMPILER_OUTPUT_WITH_BUILD_INFO_OPTION_FORMAT),
  }),
  z.object({
    id: z.string(),
    type: z.literal("hardhat-v2"),
    format: z.literal(HARDHAT_V2_COMPILER_OUTPUT_FORMAT),
  }),
  z.object({
    type: z.literal("hardhat-v3"),
    pairs: z.array(
      z.object({
        id: z.string(),
        inputFormat: z.literal(HARDHAT_V3_COMPILER_INPUT_FORMAT),
        outputFormat: z.literal(HARDHAT_V3_COMPILER_OUTPUT_FORMAT),
      }),
    ),
  }),
  z.object({
    type: z.literal("hardhat-v3-non-isolated-build"),
    id: z.string(),
    pair: z.object({
      inputFormat: z.literal(HARDHAT_V3_COMPILER_INPUT_FORMAT),
      outputFormat: z.literal(HARDHAT_V3_COMPILER_OUTPUT_FORMAT),
    }),
  }),
]);

export type EthokoArtifactOrigin = z.infer<typeof EthokoArtifactOriginSchema>;

/**
 * Input artifact schema for Ethoko storage
 */
export const EthokoInputArtifactSchema = z.object({
  id: z.string(),
  _format: z.literal("ethoko-input-v0"),
  origin: EthokoArtifactOriginSchema,
  solcLongVersion: z.string(),
  input: SolcJsonInputSchema,
});

/**
 * Output artifact schema for Ethoko storage
 */
export const EthokoContractOutputArtifactSchema = z.object({
  id: z.string(),
  // The path of the contract file in the input JSON, e.g. "contracts/MyContract.sol"
  path: z.string(),
  // The name of the contract, e.g. "MyContract"
  contract: z.string(),
  _format: z.literal("ethoko-output-v0"),
  output: z.object({
    // The contract output related to the path and contract name of the artifact, as generated by the Solidity compiler (solc).
    contract: SolcContractSchema,
    // The source related to the path of the artifact, as generated by the Solidity compiler (solc).
    source: OutputSourceSchema.optional(),
  }),
});

/**
 * Output artifact schema for Ethoko storage
 */
export const EthokoOutputArtifactSchema = z.object({
  id: z.string(),
  _format: z.literal("ethoko-output-v0"),
  output: SolcJsonOutputSchema,
});

/**
 * Tag manifest schema for tag references
 */
export const TagManifestSchema = z.object({
  id: z.string(),
});

export type EthokoInputArtifact = z.infer<typeof EthokoInputArtifactSchema>;
export type EthokoOutputArtifact = z.infer<typeof EthokoOutputArtifactSchema>;
export type EthokoContractOutputArtifact = z.infer<
  typeof EthokoContractOutputArtifactSchema
>;
export type TagManifest = z.infer<typeof TagManifestSchema>;
