import fs from "fs/promises";
import { toAsyncResult } from "@/utils/result";
import { CliError } from "./error";
import {
  inferOriginalArtifactFormat,
  InferredArtifact,
} from "@/supported-origins/infer-original-artifact-format";
import {
  mapOriginalArtifactToEthokoArtifact,
  OriginalBuildInfoPaths,
} from "@/supported-origins/map-original-artifact-to-ethoko-artifact";
import { AbsolutePath, RelativePath } from "@/utils/path";
import {
  EthokoContractOutputArtifact,
  EthokoInputArtifact,
} from "@/ethoko-artifacts/v0";
import { DebugLogger } from "@/utils/debug-logger";

/**
 * Map a candidate artifact (build info) to the Ethoko format, based on its format.
 * This function is a wrapper around the `mapOriginalArtifactToEthokoArtifact` function with CliError handling.
 * @param buildInfoPaths The paths to the candidate artifact
 * @param dependencies The dependencies for mapping, including a logger
 * @param opts Options for mapping, including debug mode
 * @returns The mapped Ethoko artifact
 */
export async function mapCandidateArtifactToEthokoArtifact(
  buildInfoPaths: OriginalBuildInfoPaths,
  dependencies: { logger: DebugLogger },
  opts: { debug: boolean },
): Promise<{
  inputArtifact: EthokoInputArtifact;
  outputContractArtifacts: EthokoContractOutputArtifact[];
  originalContent: {
    rootPath: AbsolutePath;
    paths: RelativePath[];
  };
}> {
  const ethokoArtifactParsingResult = await toAsyncResult(
    mapOriginalArtifactToEthokoArtifact(buildInfoPaths, dependencies, opts),
    { debug: opts.debug },
  );
  if (!ethokoArtifactParsingResult.success) {
    throw new CliError(
      FORMAT_TO_ERROR_MESSAGE[buildInfoPaths.format] ||
        `An error occurred while mapping the build info to Ethoko artifacts. Please provide valid build info JSON files or contact us. Run with debug mode for more info.`,
    );
  }
  return ethokoArtifactParsingResult.value;
}

const FORMAT_TO_ERROR_MESSAGE: Record<
  OriginalBuildInfoPaths["format"],
  string
> = {
  "hardhat-v3":
    "Hardhat v3 compilation artifacts have been identified but the mapping to Ethoko artifact format failed. Please provide valid Hardhat v3 compilation files or contact us. Run with debug mode for more info.",
  "hardhat-v3-non-isolated-build":
    "Hardhat v3 (non isolated build) compilation artifacts have been identified but the mapping to Ethoko artifact format failed. Please provide valid Hardhat v3 compilation files or contact us. Run with debug mode for more info.",
  "hardhat-v2":
    "Hardhat v2 compilation artifacts have been identified but the mapping to Ethoko artifact format failed. Please provide a valid Hardhat v2 build info JSON file or contact us. Run with debug mode for more info.",
  "forge-v1-with-build-info-option":
    "Forge v1 compilation artifacts with the build info option have been identified but the mapping to Ethoko artifact format failed. Please provide a valid Forge v1 build info JSON file or contact us. Run with debug mode for more info.",
  "forge-v1-default":
    "Forge v1 compilation artifacts have been identified but the mapping to Ethoko artifact format failed. Please provide a valid Forge v1 build info JSON file or contact us. Run with debug mode for more info.",
};

type CandidateBuildInfoOption = {
  label: string;
  value: OriginalBuildInfoPaths;
};

/**
 * Given the input path, look for candidate compilation artifacts (build info).
 *
 * This function is meant to be used in other CLI client methods, since it throws a CliError, it can be used without any wrapping, i.e.
 * ```ts
 * const buildInfoPath = await lookForBuildInfo(inputPath);
 * ```
 *
 * The goal is to support multiple providers of compilation artifacts, which may have different formats and structures.
 * The different supported formats are:
 * - Hardhat v2: a single JSON file containing both the input and output of the compilation, in the format generated by Hardhat v2, contained in the `build-info` directory of the Hardhat project by default
 * - Hardhat v3: muliple pairs of JSON files, one for the input of the compilation and one for the output, in the format generated by Hardhat v3, contained in the `build-info` directory of the Hardhat project by default. The input and output files are linked by a common id field in their content. A pair is emitted for each contract.
 * - Forge (default compilation mode): a single JSON file containing only an ID and references to the actual contract artifacts.
 * - Forge (with build info option): a single JSON file containing both the input and output of the compilation, in a format that is similar to Hardhat v2 but with some differences, emitted when using the `--build-info` option of Forge.
 *
 * The strategy is the following:
 * - If the inputPath is directly a JSON file:
 *  - we infer the format of the file based on its content,
 *  - if the format is recognized as a supported build info format, we return it. In case of Hardhat v3, we rebuild the pair of input/output files based on the common id field and return both paths, we don't look for other pairs.
 * - if the inputPath is a directory, we look for a `build-info` directory:
 *  - if it exists, we consider it as the main candidate to look for JSON files,
 *  - if it doesn't exist, we look for JSON files directly in the inputPath directory.
 * - for each JSON file found, we infer its format based on its content,
 * - from the inferred formats, we build the list of valid options:
 *  - Hardhat v2, Forge (default) and Forge (with build info option) files are valid on their own,
 *  - for Hardhat v3,
 *    - we gather the pairs,
 *    - we gather the pairs with the same Solc version and with creation window close (2 minutes, based on the mtime of the files) since they are more likely to be related to the same compilation,
 *    - an option is created for each of these set of pairs, with a display name containing the Solc version and the mtime of the files for the user to differentiate them.
 * The list of options is returned to the caller, as well as the count of ignored files (files that are not recognized as valid build info files) and the final folder path where the files are located (either the inputPath or the build-info directory if it exists).
 * @param inputPath The path to look for the build info JSON file
 * @param dependencies The dependencies for the function, including a logger
 * @param opts Options for the function
 * @param opts.debug Enable debug mode
 * @returns An object containing the candidate artifact options, the count of ignored files, and the final folder path
 * @throws A CliError
 */
export async function lookForCandidateArtifacts(
  inputPath: AbsolutePath,
  dependencies: { logger: DebugLogger },
  opts: { debug: boolean },
): Promise<{
  candidateBuildInfo:
    | { type: "multiple"; options: CandidateBuildInfoOption[] }
    | {
        type: "single";
        buildInfoPaths: OriginalBuildInfoPaths;
      };
  ignoredFilesCount: number;
  finalFolderPath: AbsolutePath;
}> {
  const { debug } = opts;
  const statResult = await toAsyncResult(fs.stat(inputPath.resolvedPath), {
    debug,
  });
  if (!statResult.success) {
    throw new CliError(
      `The provided path "${inputPath.resolvedPath}" does not exist or is not accessible. Please provide a valid path to a compilation artifact (build info) or a directory containing it.`,
    );
  }

  // The provided path is a file, we check if it is a valid JSON file and if it is in a supported format
  if (statResult.value.isFile()) {
    if (!inputPath.resolvedPath.endsWith(".json")) {
      throw new CliError(
        `The provided path "${inputPath.resolvedPath}" is a file but does not have a .json extension. Please provide a valid path to a JSON compilation artifact (build info).`,
      );
    }
    const contentResult = await toAsyncResult(
      fs.readFile(inputPath.resolvedPath, "utf-8").then((v) => JSON.parse(v)),
      { debug },
    );
    if (!contentResult.success) {
      throw new CliError(
        `The provided file "${inputPath.resolvedPath}" could not be read or is not a valid JSON file. Please check the file and try again. Run with debug mode for more info.`,
      );
    }

    const format = inferOriginalArtifactFormat(contentResult.value);
    if (!format.recognized) {
      throw new CliError(
        `The provided file "${inputPath}" does not seem to be a valid build info JSON file in a supported format. Please provide a valid build info JSON file. Run with debug mode for more info.`,
      );
    }
    if (
      format.artifact.format === "hardhat-v3-input-isolated-build" ||
      format.artifact.format === "hardhat-v3-input-no-isolated-build"
    ) {
      // We verify that the corresponding output file exists
      const matchingOutputPath = new AbsolutePath(
        inputPath.resolvedPath.replace(".json", ".output.json"),
      );
      const outputCheckResult = await toAsyncResult(
        fs
          .stat(matchingOutputPath.resolvedPath)
          .then(() => fs.readFile(matchingOutputPath.resolvedPath, "utf-8"))
          .then(JSON.parse)
          .then((json) => {
            const inferredFormat = inferOriginalArtifactFormat(json);
            if (
              !inferredFormat.recognized ||
              inferredFormat.artifact.format !== "hardhat-v3-output"
            ) {
              throw new Error(
                "Output file does not seem to be in hardhat v3 output format",
              );
            }
          }),
        { debug },
      );
      if (!outputCheckResult.success) {
        throw new CliError(
          `The provided file "${inputPath}" seems to be in Hardhat V3 input format, but the corresponding output file "${matchingOutputPath}" is missing or not valid. Please make sure both files are present and valid. Run with debug mode for more info.`,
        );
      }
      return {
        finalFolderPath: inputPath.dirname(),
        ignoredFilesCount: 0,
        candidateBuildInfo: {
          type: "single",
          buildInfoPaths: {
            format: "hardhat-v3",
            buildInfoPaths: [{ input: inputPath, output: matchingOutputPath }],
          },
        },
      };
    }
    if (format.artifact.format === "hardhat-v3-output") {
      // We verify that the corresponding input file exists
      const matchingInputPath = new AbsolutePath(
        inputPath.resolvedPath.replace(".output.json", ".json"),
      );
      const inputCheckResult = await toAsyncResult(
        fs
          .stat(matchingInputPath.resolvedPath)
          .then(() => fs.readFile(matchingInputPath.resolvedPath, "utf-8"))
          .then(JSON.parse)
          .then((json) => {
            const inferredFormat = inferOriginalArtifactFormat(json);
            if (
              !inferredFormat.recognized ||
              (inferredFormat.artifact.format !==
                "hardhat-v3-input-isolated-build" &&
                inferredFormat.artifact.format !==
                  "hardhat-v3-input-no-isolated-build")
            ) {
              throw new Error(
                "Input file does not seem to be in hardhat v3 input format",
              );
            }
          }),
        { debug },
      );
      if (!inputCheckResult.success) {
        throw new CliError(
          `The provided file "${inputPath}" seems to be in Hardhat V3 output format, but the corresponding input file "${matchingInputPath}" is missing or not valid. Please make sure both files are present and valid. Run with debug mode for more info.`,
        );
      }
      return {
        finalFolderPath: inputPath.dirname(),
        ignoredFilesCount: 0,
        candidateBuildInfo: {
          type: "single",
          buildInfoPaths: {
            format: "hardhat-v3",
            buildInfoPaths: [{ input: matchingInputPath, output: inputPath }],
          },
        },
      };
    }

    return {
      finalFolderPath: inputPath.dirname(),
      ignoredFilesCount: 0,
      candidateBuildInfo: {
        type: "single",
        buildInfoPaths: {
          buildInfoPath: inputPath,
          format: format.artifact.format,
        },
      },
    };
  }

  if (!statResult.value.isDirectory()) {
    throw new CliError(
      `The provided path "${inputPath}" is neither a file nor a directory. Please provide a valid path to a compilation artifact (build info) or a directory containing it.`,
    );
  }

  // We look for the directory and the entries we're gonna work with:
  // - if there is a `build-info` directory, we look for JSON files in it and consider it as the main candidate,
  // - if there is no `build-info` directory, we look for JSON files directly in the provided directory
  const entriesResult = await toAsyncResult(
    fs.readdir(inputPath.resolvedPath, { withFileTypes: true }),
    {
      debug,
    },
  );
  if (!entriesResult.success) {
    throw new CliError(
      `The provided path "${inputPath}" is a directory but could not be read. Please check the permissions and try again. Run with debug mode for more info.`,
    );
  }

  let finalEntries = entriesResult.value;
  let finalFolderPath = inputPath;

  const buildInfoDirEntry = entriesResult.value.find(
    (entry) => entry.isDirectory() && entry.name === "build-info",
  );
  if (buildInfoDirEntry) {
    const buildInfoDirPath = inputPath.join("build-info");
    const buildInfoEntriesResult = await toAsyncResult(
      fs.readdir(buildInfoDirPath.resolvedPath, { withFileTypes: true }),
      { debug },
    );
    if (!buildInfoEntriesResult.success) {
      throw new CliError(
        `The "build-info" directory in the provided path "${inputPath}" could not be read. Please check the permissions and try again. Run with debug mode for more info.`,
      );
    }
    finalFolderPath = buildInfoDirPath;
    finalEntries = buildInfoEntriesResult.value;
  }

  // We consider the JSON files
  const jsonFiles = finalEntries.filter(
    (entry) => entry.isFile() && entry.name.endsWith(".json"),
  );

  const jsonFilesWithStats: (
    | { ignored: false; summary: FileSummary }
    | { ignored: true; name: string }
  )[] = await Promise.all(
    jsonFiles.map(async (file) => {
      const filePath = finalFolderPath.join(file.name);
      const statsResult = await toAsyncResult(fs.stat(filePath.resolvedPath), {
        debug,
      });
      if (!statsResult.success) {
        if (opts.debug) {
          dependencies.logger.debug(
            `Failed to get stats for file "${filePath}". Error: ${statsResult.error}`,
          );
        }
        return {
          ignored: true as const,
          name: file.name,
        };
      }

      const inferrenceResult = await toAsyncResult(
        fs
          .readFile(filePath.resolvedPath, "utf-8")
          .then((v) => JSON.parse(v))
          .then(inferOriginalArtifactFormat),
        { debug },
      );
      if (!inferrenceResult.success) {
        if (opts.debug) {
          dependencies.logger.debug(
            `Failed to infer format for file "${filePath}". Error: ${inferrenceResult.error}`,
          );
        }
        return {
          ignored: true as const,
          name: file.name,
        };
      }
      if (!inferrenceResult.value.recognized) {
        if (opts.debug) {
          dependencies.logger.debug(
            `File "${filePath}" is not a valid build info JSON file (format inferred as "unknown"). It will be ignored.`,
          );
        }
        return {
          ignored: true as const,
          name: file.name,
        };
      }

      return {
        ignored: false as const,
        summary: {
          name: file.name,
          filePath,
          mtime: statsResult.value.mtime,
          size: statsResult.value.size,
          artifact: inferrenceResult.value.artifact,
        } satisfies FileSummary,
      };
    }),
  );

  let ignoredFilesCount = 0;
  const files: FileSummary[] = [];
  for (const file of jsonFilesWithStats) {
    if (file.ignored) {
      ignoredFilesCount++;
      continue;
    }
    files.push(file.summary);
  }

  files.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

  const options = filesToOptions(files);

  const firstOption = options[0];
  if (!firstOption) {
    throw new CliError(
      "No valid compilation artifacts were found in the provided path. Please provide a valid path to a compilation artifact (build info) or a directory containing it.",
    );
  }

  if (options.length === 1) {
    return {
      candidateBuildInfo: {
        type: "single",
        buildInfoPaths: firstOption.value,
      },
      ignoredFilesCount,
      finalFolderPath,
    };
  }

  return {
    candidateBuildInfo: {
      type: "multiple",
      options,
    },
    ignoredFilesCount,
    finalFolderPath,
  };
}

type FileSummary = {
  name: string;
  filePath: AbsolutePath;
  mtime: Date;
  size: number;
  artifact: InferredArtifact;
};
function filesToOptions(files: FileSummary[]): CandidateBuildInfoOption[] {
  const options: CandidateBuildInfoOption[] = [];
  const hardhatV3Pairs: {
    input: {
      path: AbsolutePath;
      size: number;
    };
    output: {
      path: AbsolutePath;
      size: number;
    };
    solcLongVersion: string;
    id: string;
    mtime: Date;
  }[] = [];
  for (const file of files) {
    if (file.artifact.format === "hardhat-v3-input-no-isolated-build") {
      const hardhatV3BuildInfoId = file.artifact.data.id;
      // We check if the corresponding output file is present in the list of files, if not, we ignore this file since it is not a valid build info on its own
      const matchingOutputFile = files.find(
        (f) =>
          f.artifact.format === "hardhat-v3-output" &&
          f.artifact.data.id === hardhatV3BuildInfoId,
      );
      if (!matchingOutputFile) {
        continue;
      }
      options.push({
        label: `${truncateFilename(file.name)} (Hardhat v3, Solc ${file.artifact.data.solcLongVersion}, ${formatTimeAgo(file.mtime)})`,
        value: {
          format: "hardhat-v3-non-isolated-build",
          buildInfoPaths: {
            input: file.filePath,
            output: matchingOutputFile.filePath,
          },
        },
      });
    } else if (file.artifact.format === "hardhat-v3-input-isolated-build") {
      const hardhatV3BuildInfoId = file.artifact.data.id;
      // We check if the corresponding output file is present in the list of files, if not, we ignore this file since it is not a valid build info on its own
      const matchingOutputFile = files.find(
        (f) =>
          f.artifact.format === "hardhat-v3-output" &&
          f.artifact.data.id === hardhatV3BuildInfoId,
      );
      if (!matchingOutputFile) {
        continue;
      }
      hardhatV3Pairs.push({
        solcLongVersion: file.artifact.data.solcLongVersion,
        id: hardhatV3BuildInfoId,
        mtime: file.mtime,
        input: {
          path: file.filePath,
          size: file.size,
        },
        output: {
          path: matchingOutputFile.filePath,
          size: matchingOutputFile.size,
        },
      });
    } else if (file.artifact.format === "hardhat-v3-output") {
      // Hardhat V3 output files are ignored as they will be handled together with their corresponding input file
    } else {
      options.push({
        label: `${truncateFilename(file.name)} (${BUILD_INFO_FORMAT_TO_HUMAN_READABLE[file.artifact.format]}, ${formatTimeAgo(file.mtime)}, ${formatFileSize(file.size)})`,
        value: {
          buildInfoPath: file.filePath,
          format: file.artifact.format,
        },
      });
    }
  }

  // We group the Hardhat V3 pairs by Solc version and with creation window close (2 minutes) since they are more likely to be related to the same compilation, and we create an option for each of these groups
  hardhatV3Pairs.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());
  const hardhatV3PairsGroups: {
    solcLongVersion: string;
    startWindow: Date;
    pairs: typeof hardhatV3Pairs;
  }[] = [];
  for (const pair of hardhatV3Pairs) {
    const existingGroup = hardhatV3PairsGroups.find(
      (group) =>
        group.solcLongVersion === pair.solcLongVersion &&
        Math.abs(group.startWindow.getTime() - pair.mtime.getTime()) <=
          2 * 60 * 1000,
    );
    if (existingGroup) {
      existingGroup.pairs.push(pair);
    } else {
      hardhatV3PairsGroups.push({
        solcLongVersion: pair.solcLongVersion,
        startWindow: pair.mtime,
        pairs: [pair],
      });
    }
  }
  const hardhatV3OptionGroups: CandidateBuildInfoOption[] =
    hardhatV3PairsGroups.map((group) => {
      const label = `${BUILD_INFO_FORMAT_TO_HUMAN_READABLE["hardhat-v3"]} (Solc ${group.solcLongVersion}, ${formatTimeAgo(group.startWindow)}`;
      const value: OriginalBuildInfoPaths = {
        format: "hardhat-v3",
        buildInfoPaths: group.pairs.map((pair) => ({
          input: pair.input.path,
          output: pair.output.path,
        })),
      };
      return {
        label,
        value,
      };
    });

  options.push(...hardhatV3OptionGroups);

  return options;
}

function formatTimeAgo(date: Date): string {
  const now = new Date();
  const diff = now.getTime() - date.getTime();
  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);

  if (days > 0) return `${days}d ago`;
  if (hours > 0) return `${hours}h ago`;
  if (minutes > 0) return `${minutes}m ago`;
  return "just now";
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)}MB`;
}

function truncateFilename(filename: string, maxLength: number = 60): string {
  if (filename.length <= maxLength) return filename;

  const dotIndex = filename.lastIndexOf(".");
  if (dotIndex <= 0 || dotIndex === filename.length - 1) {
    return `${filename.slice(0, Math.max(1, maxLength - 3))}...`;
  }

  const extension = filename.slice(dotIndex);
  const baseMaxLength = Math.max(1, maxLength - extension.length - 3);
  const base = filename.slice(0, baseMaxLength);
  return `${base}...${extension}`;
}

const BUILD_INFO_FORMAT_TO_HUMAN_READABLE: Record<
  OriginalBuildInfoPaths["format"],
  string
> = {
  "hardhat-v2": "Hardhat v2",
  "hardhat-v3": "Hardhat v3",
  "hardhat-v3-non-isolated-build": "Hardhat v3 (Non isolated build)",
  "forge-v1-default": "Forge",
  "forge-v1-with-build-info-option": "Forge",
};
