import { createHash } from "node:crypto";
import { LocalArtifactStore } from "@/local-artifact-store";
import { toAsyncResult, toResult } from "@/utils/result";
import { ResolvedArtifactReference } from "@/utils/artifact-reference";
import { EthokoContractOutputArtifact } from "@/ethoko-artifacts/v0";
import { CliError } from "./error";
import { DebugLogger } from "@/utils/debug-logger";

/**
 * This script generates the differences between the given artifact and an already pushed artifact.
 *
 * For each artifact, the script will work on the differences on the contracts object.
 * This object contains as keys the path of a contract file and as values the contracts within it, i.e.
 * ```
 * {
 *  "output": {
 *   "contracts": {
 *      "path/to/foo.sol": {
 *         "Foo": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         }
 *      },
 *      "path/to/bar.sol": {
 *         "Bar1": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         },
 *         "Bar2": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         },
 *      },
 *   }
 * }
 * ```
 *
 * For each contract, a hash is computed based on
 * - stringified abi,
 * - bytecode object,
 * - metadata
 * This hash is stored in a map with the `<file path><separator constant><contract name>` as key.
 *
 * Comparing the two maps, the script will output the differences between the two sets of contracts.
 */
export type Difference = {
  path: string;
  name: string;
  status: "added" | "removed" | "changed";
};

/**
 * Generates the differences between the artifacts generated by a candidate compilation artifact and the ones of a target artifact already pulled.
 *
 * The method will check if the target artifact exists locally, if not, an error is thrown,
 * The target contract artifacts are retrieved,
 * It will then generate one digest map for the contracts for the target artifact, another one for the candidate artifact,
 * Finally, the two maps are compared and the differences are generated
 *
 * @throws CliError if there is an error during the execution of the steps, with user-friendly messages that can be directly shown to the user
 * @param targetArtifactReference The reference to the target artifact, containing the project, the id and optionally the tag of the target artifact
 * @param candidateArtifact The candidate compilation artifact to compare with the target artifact
 * @param dependencies The dependencies
 * @param opts Options for the diff command
 * @param opts.debug Enable debug mode for more verbose logging
 * @returns The array of differences between the fresh compilation artifact and the target artifact
 */
export async function generateDiffWithTargetRelease(
  targetArtifactReference: ResolvedArtifactReference,
  candidateArtifact: {
    outputContractArtifacts: EthokoContractOutputArtifact[];
  },
  dependencies: {
    localArtifactStore: LocalArtifactStore;
    logger: DebugLogger;
  },
  opts: { debug: boolean },
): Promise<Difference[]> {
  const ensureResult = await toAsyncResult(
    dependencies.localArtifactStore.ensureProjectSetup(
      targetArtifactReference.project,
    ),
    { debug: opts.debug },
  );
  if (!ensureResult.success) {
    throw new CliError(
      "Error setting up Local Artifact Store, is the script not allowed to write to the filesystem? Run with debug mode for more info",
    );
  }

  const candidateContractHashesResult = toResult(
    () => generateContractHashes(candidateArtifact.outputContractArtifacts),
    { debug: opts.debug },
  );
  if (!candidateContractHashesResult.success) {
    throw new CliError(
      "Error generating contract hashes from the candidate compilation artifact. Run with debug mode for more info",
    );
  }
  if (opts.debug) {
    dependencies.logger.debug(
      `Candidate contract hashes generated successfully: ${[...candidateContractHashesResult.value.entries()].map(([key, hash]) => `\n${key}: ${hash}`).join("")}`,
    );
  }

  const targetContractsResult = await toAsyncResult(
    dependencies.localArtifactStore
      .listContractArtifacts(
        targetArtifactReference.project,
        targetArtifactReference.id,
      )
      .then((commonContracts) =>
        Promise.all(
          commonContracts.map((c) =>
            dependencies.localArtifactStore.retrieveContractOutputArtifact(
              targetArtifactReference.project,
              targetArtifactReference.id,
              c.sourceName,
              c.contractName,
            ),
          ),
        ),
      ),
    { debug: opts.debug },
  );
  if (!targetContractsResult.success) {
    throw new CliError(
      "Unable to retrieve the target artifact content, please ensure it exists locally. Run with debug mode for more info",
    );
  }
  if (opts.debug) {
    dependencies.logger.debug(
      `Target contract artifacts retrieved successfully: ${targetContractsResult.value.map((c) => `\n${c.sourceName} - ${c.contract}`).join("")}`,
    );
  }

  const targetContractHashesResult = toResult(
    () => generateContractHashes(targetContractsResult.value),
    { debug: opts.debug },
  );
  if (!targetContractHashesResult.success) {
    throw new CliError(
      "Error generating contract hashes for the target artifact. Run with debug mode for more info",
    );
  }
  if (opts.debug) {
    dependencies.logger.debug(
      `Target contract hashes generated successfully: ${[...targetContractHashesResult.value.entries()].map(([key, hash]) => `\n${key}: ${hash}`).join("")}`,
    );
  }

  const differences: Difference[] = [];
  for (const [
    contractKey,
    contractHash,
  ] of candidateContractHashesResult.value.entries()) {
    const { contractPath, contractName } = parseKey(contractKey);
    const targetReleaseHash = targetContractHashesResult.value.get(contractKey);
    if (!targetReleaseHash) {
      differences.push({
        path: contractPath,
        name: contractName,
        status: "added",
      });
    } else if (targetReleaseHash !== contractHash) {
      differences.push({
        path: contractPath,
        name: contractName,
        status: "changed",
      });
    }
  }

  for (const contractKey of targetContractHashesResult.value.keys()) {
    if (!candidateContractHashesResult.value.has(contractKey)) {
      const { contractPath, contractName } = parseKey(contractKey);
      differences.push({
        path: contractPath,
        name: contractName,
        status: "removed",
      });
    }
  }

  if (opts.debug) {
    dependencies.logger.debug(
      `Differences calculated successfully: ${differences.map((d) => `\n${d.path} - ${d.name}: ${d.status}`).join("")}`,
    );
  }

  return differences;
}

function generateContractHashes(
  contractArtifacts: EthokoContractOutputArtifact[],
): Map<string, string> {
  const contractHashes = new Map<string, string>();
  for (const contractArtifact of contractArtifacts) {
    const hash = hashContract(contractArtifact.output.contract);
    contractHashes.set(
      formKey(contractArtifact.sourceName, contractArtifact.contract),
      hash,
    );
  }

  return contractHashes;
}

type Contract = EthokoContractOutputArtifact["output"]["contract"];
function hashContract(contract: Contract): string {
  const hash = createHash("sha256");

  contract.abi.sort((a, b) => {
    if (a.type !== b.type) {
      return a.type.localeCompare(b.type);
    }
    if (a.type === "function" && b.type === "function") {
      return a.name.localeCompare(b.name);
    }
    if (a.type === "event" && b.type === "event") {
      return a.name.localeCompare(b.name);
    }
    if (a.type === "error" && b.type === "error") {
      return a.name.localeCompare(b.name);
    }
    if (a.type === "constructor" && b.type === "constructor") {
      return 0;
    }
    if (a.type === "fallback" && b.type === "fallback") {
      return 0;
    }
    if (a.type === "receive" && b.type === "receive") {
      return 0;
    }
    return 0;
  });
  for (const abiItem of contract.abi) {
    hash.update(JSON.stringify(abiItem));
  }

  hash.update(contract.evm.bytecode.object);
  hash.update(contract.metadata);

  return hash.digest("hex");
}

const SEPARATOR = "@@@@";
function formKey(contractPath: string, contractName: string): string {
  return `${contractPath}${SEPARATOR}${contractName}`;
}
function parseKey(key: string): { contractPath: string; contractName: string } {
  const [contractPath, contractName] = key.split(SEPARATOR);
  if (!contractPath || !contractName) {
    throw new Error(`Invalid key: ${key}`);
  }
  return { contractPath, contractName };
}
