import { createHash } from "node:crypto";
import { CommandLogger } from "../ui";
import { PulledArtifactStore } from "../pulled-artifact-store/pulled-artifact-store";
import { toAsyncResult, toResult } from "../utils/result";
import { CliError } from "./error";
import {
  lookForCandidateArtifacts,
  promptUserSelection,
} from "./helpers/look-for-candidate-artifacts";
import { EthokoContractOutputArtifact } from "@/ethoko-artifacts/v0";
import {
  mapOriginalArtifactToEthokoArtifact,
  OriginalBuildInfoPaths,
} from "@/supported-origins/map-original-artifact-to-ethoko-artifact";
import { AbsolutePath } from "@/utils/path";
import { retrieveOrPullArtifact } from "./helpers/retrieve-or-pull-artifact";
import { StorageProvider } from "@/storage-provider";
import { ArtifactKey } from "@/utils/artifact-key";

function buildInfoPathToSuccessText(paths: OriginalBuildInfoPaths): string {
  if (paths.format === "hardhat-v3") {
    return `Hardhat v3 compilation artifact found`;
  }
  if (paths.format === "hardhat-v3-non-isolated-build") {
    return `Hardhat v3 compilation artifact found (non isolated build)`;
  }
  if (paths.format === "hardhat-v2") {
    return `Hardhat v2 compilation artifact input file found at ${paths.buildInfoPath}`;
  }
  if (
    paths.format === "forge-v1-default" ||
    paths.format === "forge-v1-with-build-info-option"
  ) {
    return `Forge compilation artifact found at ${paths.buildInfoPath}`;
  }
  throw new CliError(
    `Unsupported build info format: ${paths.format satisfies never}`,
  );
}

const FORMAT_TO_ERROR_MESSAGE: Record<
  OriginalBuildInfoPaths["format"],
  string
> = {
  "hardhat-v3":
    "Hardhat v3 compilation artifacts have been identified but the mapping to Ethoko artifact format failed. Please provide valid Hardhat v3 compilation files or contact us. Run with debug mode for more info.",
  "hardhat-v3-non-isolated-build":
    "Hardhat v3 (non isolated build) compilation artifacts have been identified but the mapping to Ethoko artifact format failed. Please provide valid Hardhat v3 compilation files or contact us. Run with debug mode for more info.",
  "hardhat-v2":
    "Hardhat v2 compilation artifacts have been identified but the mapping to Ethoko artifact format failed. Please provide a valid Hardhat v2 build info JSON file or contact us. Run with debug mode for more info.",
  "forge-v1-with-build-info-option":
    "Forge v1 compilation artifacts with the build info option have been identified but the mapping to Ethoko artifact format failed. Please provide a valid Forge v1 build info JSON file or contact us. Run with debug mode for more info.",
  "forge-v1-default":
    "Forge v1 compilation artifacts have been identified but the mapping to Ethoko artifact format failed. Please provide a valid Forge v1 build info JSON file or contact us. Run with debug mode for more info.",
};

/**
 * This script generates the differences between the artifacts generated by a fresh compilation and the ones of a pulled artifact.
 *
 * The fresh artifacts are represented by the file at `artifacts/build-info/<build info hash>.json`.
 * The `latest` artifacts are represented by the file at `<Ethoko directory>/<release>/build-info.json`.
 *
 * For each build info file, the script will parse the `output.contracts` object.
 * This object contains as keys the path of a contract file and as values the contracts within it, i.e.
 * ```
 * {
 *  "output": {
 *   "contracts": {
 *      "path/to/foo.sol": {
 *         "Foo": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         }
 *      },
 *      "path/to/bar.sol": {
 *         "Bar1": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         },
 *         "Bar2": {
 *             "abi": [...],
 *             "devdoc": {...},
 *             "evm": {
 *                "bytecode": {...},
 *                "deployedBytecode": {...},
 *                ...
 *             },
 *             "metadata": "...",
 *             "storageLayout": {...},
 *             "userdoc": {...}
 *         },
 *      },
 *   }
 * }
 * ```
 *
 * For each contract, a hash is computed based on
 * - stringified abi,
 * - bytecode object,
 * - metadata
 * This hash is stored in a map with the `<file path><separator constant><contract name>` as key.
 *
 * Comparing the two maps, the script will output the differences between the two sets of contracts.
 */
export type Difference = {
  path: string;
  name: string;
  status: "added" | "removed" | "changed";
};

/**
 * Generates the differences between the artifacts generated by a fresh compilation and the ones of a pulled artifact.
 * It consists of the following steps:
 * 1. Check if the target artifact exists locally, if not throw an error
 * 2. Read the build info file of the fresh compilation artifact and generate the contract hashes map
 * 3. Read the build info file of the target artifact and generate the contract hashes map
 * 4. Compare the two maps and generate the differences array
 *
 * @throws CliError if there is an error during the execution of the steps, with user-friendly messages that can be directly shown to the user
 * @param artifactPath The path to the artifact to compare with,
 * @param artifact The artifact to compare with, containing the project and the tag or id of the target artifact
 * @param storageProvider The StorageProvider instance to use for retrieving the target artifact if it's not available locally
 * @param pulledArtifactStore The store used to persist pulled artifacts
 * @param opts Options for the diff command
 * @param opts.debug Enable debug mode for more verbose logging
 * @param opts.logger The CommandLogger instance to use for logging and prompting the user during the diff process
 * @param opts.isCI Whether running in CI environment (disables interactive prompts)
 * @returns The array of differences between the fresh compilation artifact and the target artifact
 */
export async function generateDiffWithTargetRelease(
  artifactPath: AbsolutePath,
  artifactKey: ArtifactKey,
  storageProvider: StorageProvider,
  pulledArtifactStore: PulledArtifactStore,
  opts: { debug: boolean; logger: CommandLogger; isCI?: boolean },
): Promise<Difference[]> {
  // Step 1: Check if target artifact exists locally

  const spinner1 = opts.logger.createSpinner(
    "Checking artifact existence locally...",
  );
  const ensureResult = await toAsyncResult(
    pulledArtifactStore.ensureProjectSetup(artifactKey.project),
    { debug: opts.debug },
  );
  if (!ensureResult.success) {
    spinner1.fail("Failed to setup pulled artifact store");
    throw new CliError(
      "Error setting up pulled artifact store, is the script not allowed to write to the filesystem? Run with debug mode for more info",
    );
  }

  const artifactId = await retrieveOrPullArtifact(
    artifactKey,
    storageProvider,
    pulledArtifactStore,
    { debug: opts.debug, logger: opts.logger },
  ).catch((err) => {
    spinner1.fail("Failed to retrieve or pull the target artifact");
    throw err;
  });
  spinner1.succeed("Artifact found");

  // Step 2: Look for compilation artifact
  const spinner2 = opts.logger.createSpinner(
    "Looking for compilation artifact...",
  );
  const candidateArtifactsResult = await toAsyncResult(
    lookForCandidateArtifacts(artifactPath, {
      debug: opts.debug,
    }),
  );
  if (!candidateArtifactsResult.success) {
    spinner2.fail("Failed to find compilation artifact");
    // @dev the lookForCandidateArtifacts function throws a CliError with a user-friendly message, so we can directly re-throw it here without wrapping it in another error or modifying the message
    throw candidateArtifactsResult.error;
  }
  const firstBuildInfoCandidate =
    candidateArtifactsResult.value.candidateBuildInfoOptions[0];
  if (!firstBuildInfoCandidate) {
    spinner2.fail("No valid compilation artifacts found");
    throw new CliError(
      "No valid compilation artifacts were found in the provided path. Please provide a valid path to a compilation artifact (build info) or a directory containing it.",
    );
  }

  let selectedBuildInfoPaths: OriginalBuildInfoPaths;
  if (candidateArtifactsResult.value.candidateBuildInfoOptions.length === 1) {
    selectedBuildInfoPaths = firstBuildInfoCandidate.value;
  } else {
    if (opts.isCI) {
      spinner2.fail("Multiple compilation artifacts found");
      throw new CliError(
        "Multiple compilation artifacts were found in the provided path. Please provide a more specific path or run the command in interactive mode to select the desired artifact.",
      );
    }
    const userSelectionResult = await toAsyncResult(
      promptUserSelection(
        opts.logger,
        `Multiple JSON files found in "${candidateArtifactsResult.value.finalFolderPath}" (${candidateArtifactsResult.value.ignoredFilesCount} ignored). Please select which build info file to use:`,
        candidateArtifactsResult.value.candidateBuildInfoOptions,
        30_000,
      ),
      { debug: opts.debug },
    );
    if (!userSelectionResult.success) {
      spinner2.fail("No compilation artifact selected");
      // @dev the promptUserSelection function throws a CliError with a user-friendly message, so we can directly re-throw it here without wrapping it in another error or modifying the message
      throw userSelectionResult.error;
    }
    selectedBuildInfoPaths = userSelectionResult.value;
  }
  spinner2.succeed(buildInfoPathToSuccessText(selectedBuildInfoPaths));

  // Step 3: Parse the compilation artifact, mapping it to the Ethoko format
  const spinner3 = opts.logger.createSpinner(
    "Analyzing compilation artifact...",
  );
  const ethokoArtifactParsingResult = await toAsyncResult(
    mapOriginalArtifactToEthokoArtifact(selectedBuildInfoPaths, opts.debug),
    { debug: opts.debug },
  );
  if (!ethokoArtifactParsingResult.success) {
    spinner3.fail("Unable to handle the provided compilation artifact");
    throw new CliError(
      FORMAT_TO_ERROR_MESSAGE[selectedBuildInfoPaths.format] ||
        `An error occurred while mapping the build info to Ethoko artifacts. Please provide valid build info JSON files or contact us. Run with debug mode for more info.`,
    );
  }
  const contractArtifacts =
    ethokoArtifactParsingResult.value.outputContractArtifacts;
  spinner3.succeed("Compilation artifact is valid");

  const virtualReleaseContractHashesResult = toResult(
    () => generateContractHashes(contractArtifacts),
    { debug: opts.debug },
  );
  if (!virtualReleaseContractHashesResult.success) {
    spinner3.fail("Failed to analyze compilation artifact");
    throw new CliError(
      "Error generating contract hashes from the fresh compilation artifact. Run with debug mode for more info",
    );
  }
  spinner3.succeed("Fresh artifact loaded");

  const spinner4 = opts.logger.createSpinner("Reading target artifact...");
  const contractListResult = await toAsyncResult(
    pulledArtifactStore.listContractArtifacts(artifactKey.project, artifactId),
    { debug: opts.debug },
  );
  if (!contractListResult.success) {
    spinner4.fail("Failed to read target artifact");
    throw new CliError(
      "Unable to retrieve the target artifact content, please ensure it exists locally. Run with debug mode for more info",
    );
  }

  const commonContracts = contractListResult.value.filter((contract) =>
    virtualReleaseContractHashesResult.value.has(
      formKey(contract.sourceName, contract.contractName),
    ),
  );

  const commonContractArtifactsResult = await toAsyncResult(
    Promise.all(
      commonContracts.map((contract) =>
        pulledArtifactStore.retrieveContractOutputArtifact(
          artifactKey.project,
          artifactId,
          contract.sourceName,
          contract.contractName,
        ),
      ),
    ),
    { debug: opts.debug },
  );
  if (!commonContractArtifactsResult.success) {
    spinner4.fail("Failed to read target artifact");
    throw new CliError(
      "Unable to retrieve the target artifact content, please ensure it exists locally. Run with debug mode for more info",
    );
  }

  const targetReleaseContractHashesResult = toResult(
    () => generateContractHashes(commonContractArtifactsResult.value),
    { debug: opts.debug },
  );
  if (!targetReleaseContractHashesResult.success) {
    spinner4.fail("Failed to analyze target artifact");
    throw new CliError(
      "Error generating contract hashes for the target artifact. Run with debug mode for more info",
    );
  }
  spinner4.succeed("Target artifact loaded");

  const spinner5 = opts.logger.createSpinner("Computing differences...");
  const differences: Difference[] = [];
  for (const [
    contractKey,
    contractHash,
  ] of virtualReleaseContractHashesResult.value.entries()) {
    const { contractPath, contractName } = parseKey(contractKey);
    const targetReleaseHash =
      targetReleaseContractHashesResult.value.get(contractKey);
    if (!targetReleaseHash) {
      differences.push({
        path: contractPath,
        name: contractName,
        status: "added",
      });
    } else if (targetReleaseHash !== contractHash) {
      differences.push({
        path: contractPath,
        name: contractName,
        status: "changed",
      });
    }
  }

  for (const contractKey of targetReleaseContractHashesResult.value.keys()) {
    if (!virtualReleaseContractHashesResult.value.has(contractKey)) {
      const { contractPath, contractName } = parseKey(contractKey);
      differences.push({
        path: contractPath,
        name: contractName,
        status: "removed",
      });
    }
  }
  spinner5.succeed("Differences computed");

  return differences;
}

function generateContractHashes(
  contractArtifacts: EthokoContractOutputArtifact[],
): Map<string, string> {
  const contractHashes = new Map<string, string>();
  for (const contractArtifact of contractArtifacts) {
    const hash = hashContract(contractArtifact.output.contract);
    contractHashes.set(
      formKey(contractArtifact.sourceName, contractArtifact.contract),
      hash,
    );
  }

  return contractHashes;
}

type Contract = EthokoContractOutputArtifact["output"]["contract"];
function hashContract(contract: Contract): string {
  const hash = createHash("sha256");

  contract.abi.sort((a, b) => {
    if (a.type !== b.type) {
      return a.type.localeCompare(b.type);
    }
    if (a.type === "function" && b.type === "function") {
      return a.name.localeCompare(b.name);
    }
    if (a.type === "event" && b.type === "event") {
      return a.name.localeCompare(b.name);
    }
    if (a.type === "error" && b.type === "error") {
      return a.name.localeCompare(b.name);
    }
    if (a.type === "constructor" && b.type === "constructor") {
      return 0;
    }
    if (a.type === "fallback" && b.type === "fallback") {
      return 0;
    }
    if (a.type === "receive" && b.type === "receive") {
      return 0;
    }
    return 0;
  });
  for (const abiItem of contract.abi) {
    hash.update(JSON.stringify(abiItem));
  }

  hash.update(contract.evm.bytecode.object);
  hash.update(contract.metadata);

  return hash.digest("hex");
}

const SEPARATOR = "@@@@";
function formKey(contractPath: string, contractName: string): string {
  return `${contractPath}${SEPARATOR}${contractName}`;
}
function parseKey(key: string): { contractPath: string; contractName: string } {
  const [contractPath, contractName] = key.split(SEPARATOR);
  if (!contractPath || !contractName) {
    throw new Error(`Invalid key: ${key}`);
  }
  return { contractPath, contractName };
}
