import { beforeAll, describe, test } from "vitest";
import fs from "fs/promises";
import { asyncExec } from "./async-exec.js";
import { E2E_FOLDER_PATH } from "./e2e-folder-path.js";
import crypto from "crypto";

export function hardhatDescribe(args: {
  title: string;
  runner: "hardhat" | "cli";
}) {
  const { title, runner } = args;
  const testId = `${runner}-${crypto.randomBytes(8).toString("hex")}`;
  const tag = testId;
  // We keep hardhat file at the root as a nested one is not supported by Hardhat v2
  const hardhatConfigPath = `hardhat.config.e2e.${testId}.ts`;
  const cliConfigPath = `${E2E_FOLDER_PATH}/ethoko.config.e2e.${testId}.json`;
  const deploymentScriptFolderPath = `${E2E_FOLDER_PATH}/deploy-${testId}`;
  const generatedArtifactsPath = `${E2E_FOLDER_PATH}/generated-artifacts-${testId}`;

  const ethokoCommand =
    runner === "hardhat"
      ? `npx hardhat --config ${hardhatConfigPath} ethoko`
      : `npx ethoko --config ${cliConfigPath}`;

  describe(title, () => {
    beforeAll(async () => {
      // We create:
      // - A temporary Hardhat config file based on the template, with the appropriate placeholders replaced with the actual values for this test
      // - A temporary hardhat-deploy deployment script based on the template, with the appropriate placeholders replaced with the actual values for this test
      // - if the runner is CLI, we create a temporary config file for the CLI as well
      const hardhatConfigTemplate = await fs.readFile(
        "e2e-test/hardhat.config.e2e.template.ts",
        "utf-8",
      );
      const hardhatConfigContent = hardhatConfigTemplate
        .replace(
          "PULLED_ARTIFACTS_PATH",
          `${E2E_FOLDER_PATH}/pulled-artifacts-${testId}`,
        )
        .replace("ARTIFACTS_PATH", generatedArtifactsPath)
        .replace("TYPINGS_PATH", `${E2E_FOLDER_PATH}/typings-${testId}`)
        .replace("STORAGE_PATH", `${E2E_FOLDER_PATH}/storage-${testId}`);

      await fs.writeFile(hardhatConfigPath, hardhatConfigContent);

      if (runner === "cli") {
        const cliConfigTemplate = await fs.readFile(
          "e2e-test/ethoko.config.e2e.template.json",
          "utf-8",
        );
        const cliConfigContent = cliConfigTemplate
          .replace(
            "PULLED_ARTIFACTS_PATH",
            `./../${E2E_FOLDER_PATH}/pulled-artifacts-${testId}`,
          )
          .replace("TYPINGS_PATH", `./../${E2E_FOLDER_PATH}/typings-${testId}`)
          .replace("STORAGE_PATH", `./../${E2E_FOLDER_PATH}/storage-${testId}`);
        await fs.writeFile(cliConfigPath, cliConfigContent);
      }

      await fs.mkdir(deploymentScriptFolderPath, { recursive: true });

      const deploymentScriptContent = await fs.readFile(
        "deploy/00-deploy-counter-2026-02-04.ts",
        "utf-8",
      );
      const updatedScriptContent = deploymentScriptContent
        .replace(/2026-02-04/g, tag)
        .replace("../.ethoko-typings", `../typings-${testId}`);

      await fs.writeFile(
        `${deploymentScriptFolderPath}/00-deploy-counter-${tag}.ts`,
        updatedScriptContent,
      );

      return async () => {
        await fs.rm(hardhatConfigPath);
      };
    });

    test("it compiles", () =>
      asyncExec(
        `npx hardhat compile --force --no-typechain --config ${hardhatConfigPath}`,
      ));

    test("it pushes the tag", () =>
      asyncExec(
        `${ethokoCommand} push --tag ${tag} --artifact-path ${generatedArtifactsPath}`,
      ));

    test("it pulls the tag", () => asyncExec(`${ethokoCommand} pull`));

    test("it generates the typings", () =>
      asyncExec(`${ethokoCommand} typings`));

    test("it checks types", () => asyncExec("pnpm tsc --noEmit"));

    // TODO: typings generated by the CLI are for NodeNext target, which causes issues on Hardhat v2 CJS environment.
    test.skipIf(() => runner === "cli")("it deploys", () =>
      asyncExec(
        `npx hardhat --config ${hardhatConfigPath} deploy --no-compile --deploy-scripts ${deploymentScriptFolderPath}`,
      ),
    );

    test("it restores the original artifacts", async () => {
      await asyncExec(
        `${ethokoCommand} restore --tag ${tag} --output ./${E2E_FOLDER_PATH}/restored-artifacts-${tag}`,
      );
      await asyncExec(`ls -la ./${E2E_FOLDER_PATH}/restored-artifacts-${tag}`);
    });
  });
}
