name: Trigger E2E tests for https://github.com/VGLoic/v4-core-ethoko-test
on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    trigger-uniswap-v4-core-ethoko-test-e2e:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger E2E tests in VGLoic/v4-core-ethoko-test repository
              run: |
                repo_owner="VGLoic"
                repo_name="v4-core-ethoko-test"
                event_type="trigger-e2e-tests"
                curl -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.PAT_UNI_FORK_TEST }}" \
                  https://api.github.com/repos/${repo_owner}/${repo_name}/dispatches \
                  -d "{\"event_type\":\"${event_type}\"}"
