import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";
import { project } from "../../.ethoko-typings";

/**
 * This deployment script deploys the contracts targeting a specific release.
 *
 * The compilation artifacts are retrieved from the Ethoko project registry for the specified release.
 * The artifacts are **frozen** at the time of the release, ensuring consistent deployments.
 * Local modifications to the contract source code or any new compilation, releases etc.. will not affect this deployment.
 *
 * The `Oracle` contract is deployed first.
 * Then the `ExternalMath` library is deployed.
 * Finally, the `Counter` contract is deployed, linking the `ExternalMath` library and using the address of the deployed `Oracle`.
 * The deployment is done using `Hardhat Ignition`.
 *
 * This script relies on typings generated by Ethoko for the project "verified-forge-counter".
 * It is assumed that the tag `2026-02-02` exists in the Ethoko registry for this project.
 * It could have been created by running:
 * ```
 * npx hardhat ethoko push --tag 2026-02-02
 * ```
 * The assumed commands that have been run prior to this deployment are:
 *  - `npx hardhat ethoko pull` to pull the project from the Ethoko registry,
 *  - `npx hardhat ethoko typings` to generate the typings for the project.
 */

const TARGET_RELEASE_TAG = "2026-02-02";
// Hardhat Ignition likes alphanumeric and underscores
const MODULE_SUFFIX = TARGET_RELEASE_TAG.replaceAll("-", "_");

export default buildModule(`release_${MODULE_SUFFIX}`, (m) => {
  const projectUtils = project("verified-forge-counter");

  const oracleArtifact = projectUtils
    .tag(TARGET_RELEASE_TAG)
    // Hardhat Ignition module does not support promises => we use the `sync` variant of artifact retrieval
    .getContractArtifactSync("src/Oracle.sol:Oracle");

  const oracle = m.contract("Oracle", oracleArtifact, [m.getAccount(0)]);

  const externalMathLibArtifact = projectUtils
    .tag(TARGET_RELEASE_TAG)
    .getContractArtifactSync("src/ExternalMath.sol:ExternalMath");

  const externalMathLib = m.library("ExternalMath", externalMathLibArtifact);

  const counterArtifact = projectUtils
    .tag(TARGET_RELEASE_TAG)
    .getContractArtifactSync("src/Counter.sol:Counter");

  const counter = m.contract("Counter", counterArtifact, [oracle], {
    libraries: {
      ExternalMath: externalMathLib,
    },
  });

  return { counter, oracle, externalMathLib };
});
